#pragma once

#include "core.hpp"

#include <string>
#include <vector>

namespace magic_geo::detail {

struct FeedbackReference {
    std::vector<double> elevation_m;
    std::vector<double> temperature_c;
    std::vector<double> precipitation_mm_y;
    std::vector<double> runoff_mm_y;
};

struct NumericDepressionFillEvent {
    int id = 0;
    int feedback_stage_id = 0;
    std::string stage;
    int erosion_iteration = -1;
    int stabilization_pass = 0;
    int source_depression_component_id = -1;
    int sink_cell_id = -1;
    int sink_crust_type = 0;
    bool sink_is_geologic = false;
    double sink_boundary_divergent = 0.0;
    double sink_boundary_convergent = 0.0;
    std::vector<int> cell_ids;
    std::vector<double> elevation_before_fill_m_by_cell;
    std::vector<double> sediment_thickness_before_correction_m_by_cell;
    std::vector<double> fill_depth_m_by_cell;
    std::vector<double> elevation_after_fill_m_by_cell;
    double area_km2 = 0.0;
    double fill_volume_km3 = 0.0;
    double max_fill_depth_m = 0.0;
    bool breach_feasible = false;
    int breach_outlet_cell_id = -1;
    std::vector<int> breach_path_cell_ids;
    std::vector<double> breach_elevation_before_m_by_cell;
    std::vector<double> breach_target_elevation_m_by_cell;
    std::vector<double> breach_excavation_depth_m_by_cell;
    std::vector<double> breach_sediment_thickness_before_excavation_m_by_cell;
    std::vector<double> breach_alluvium_entrainment_depth_m_by_cell;
    std::vector<double> breach_bedrock_erosion_depth_m_by_cell;
    double breach_path_length_km = 0.0;
    double breach_excavation_area_km2 = 0.0;
    double breach_excavation_volume_km3 = 0.0;
    double max_breach_excavation_depth_m = 0.0;
    double breach_to_fill_volume_ratio = 0.0;
    bool breach_has_lower_adjustment_volume = false;
    bool breach_depth_bound_passed = false;
    bool breach_deposition_capacity_sufficient = false;
    bool breach_same_pass_conflict_free = false;
    bool breach_selected = false;
    bool temporary_numeric_lake_selected = false;
    double breach_deposition_capacity_km3 = 0.0;
    std::vector<int> breach_deposition_cell_ids;
    std::vector<double> breach_deposition_depth_m_by_cell;
    double applied_fill_volume_km3 = 0.0;
    double applied_breach_excavation_volume_km3 = 0.0;
    double applied_breach_deposition_volume_km3 = 0.0;
    double applied_alluvium_entrainment_volume_km3 = 0.0;
    double applied_bedrock_erosion_volume_km3 = 0.0;
    double correction_mass_balance_residual_km3 = 0.0;
};

struct HydrologyStabilizationResult {
    int sea_level_recompute_count = 0;
    int climate_recompute_count = 0;
    int hydrologic_water_budget_recompute_count = 0;
    int hydrology_recompute_count = 0;
    int numeric_depression_fill_pass_count = 0;
    int numeric_depression_fill_event_count = 0;
    int numeric_depression_fill_cell_application_count = 0;
    int numeric_depression_filled_unique_cell_count = 0;
    int numeric_depression_correction_event_count = 0;
    int numeric_depression_breach_selected_event_count = 0;
    int numeric_depression_breach_excavation_cell_application_count = 0;
    int numeric_depression_breach_deposition_cell_application_count = 0;
    int numeric_depression_temporary_lake_event_count = 0;
    int numeric_depression_temporary_lake_cell_application_count = 0;
    int numeric_depression_temporary_lake_unique_cell_count = 0;
    double sea_level_adjustment_m = 0.0;
    double numeric_depression_fill_area_km2 = 0.0;
    double numeric_depression_fill_volume_km3 = 0.0;
    double max_numeric_depression_fill_depth_m = 0.0;
    double numeric_depression_breach_excavation_volume_km3 = 0.0;
    double numeric_depression_breach_deposition_volume_km3 = 0.0;
    double numeric_depression_alluvium_entrainment_volume_km3 = 0.0;
    double numeric_depression_bedrock_erosion_volume_km3 = 0.0;
    double numeric_depression_correction_mass_balance_residual_km3 = 0.0;
    double numeric_depression_temporary_lake_candidate_area_km2 = 0.0;
    double numeric_depression_temporary_lake_candidate_volume_km3 = 0.0;
    double max_numeric_depression_temporary_lake_depth_m = 0.0;
};

struct HydrologicWaterBudgetStage {
    int id = 0;
    int feedback_stage_id = 0;
    int erosion_iteration = -1;
    int stabilization_recomputation_index = 0;
    std::string stage;
    int cell_count = 0;
    int land_cell_count = 0;
    int marine_cell_count = 0;
    double land_precipitation_volume_km3_y = 0.0;
    double actual_evapotranspiration_volume_km3_y = 0.0;
    double infiltration_volume_km3_y = 0.0;
    double runoff_volume_km3_y = 0.0;
    double mass_balance_residual_km3_y = 0.0;
    double max_abs_cell_residual_mm_y = 0.0;
    std::vector<int> cell_ids;
    std::vector<int> is_marine_by_cell;
    std::vector<int> lithology_by_cell;
    std::vector<double> cell_area_km2_by_cell;
    std::vector<double> elevation_m_by_cell;
    std::vector<double> temperature_c_by_cell;
    std::vector<double> precipitation_mm_y_by_cell;
    std::vector<double> local_relief_m_by_cell;
    std::vector<double> sediment_thickness_m_by_cell;
    std::vector<double> ice_thickness_m_by_cell;
    std::vector<double> potential_evapotranspiration_mm_y_by_cell;
    std::vector<double> infiltration_capacity_index_by_cell;
    std::vector<double> actual_evapotranspiration_mm_y_by_cell;
    std::vector<double> infiltration_mm_y_by_cell;
    std::vector<double> water_balance_mm_y_by_cell;
    std::vector<double> runoff_mm_y_by_cell;
    std::vector<double> residual_mm_y_by_cell;
};

struct FluvialSedimentRoutingCellStep {
    int cell_id = -1;
    int flow_to_cell_id = -1;
    int depression_component_id = -1;
    int depression_sink_cell_id = -1;
    int water_body = 0;
    bool is_water = false;
    bool is_river = false;
    bool is_lake = false;
    bool lake_overflows = false;
    bool is_land_terminal = false;
    bool is_marine_terminal = false;
    double cell_area_km2 = 0.0;
    double flow_accumulation = 0.0;
    double runoff_mm_y = 0.0;
    double hydrologic_flow_slope = 0.0;
    double routing_base_elevation_m = 0.0;
    double spill_elevation_m = 0.0;
    double local_source_volume_km3 = 0.0;
    double incoming_volume_km3 = 0.0;
    double available_volume_km3 = 0.0;
    double transport_capacity_fraction = 0.0;
    double depression_accommodation_volume_km3 = 0.0;
    double capacity_deposition_volume_km3 = 0.0;
    double depression_fill_deposition_volume_km3 = 0.0;
    double lake_trap_deposition_volume_km3 = 0.0;
    double marine_deposition_volume_km3 = 0.0;
    double routed_outgoing_volume_km3 = 0.0;
    double terminal_land_storage_volume_km3 = 0.0;
    double terminal_export_volume_km3 = 0.0;
    double local_mass_balance_residual_km3 = 0.0;
};

struct FluvialSedimentTerminalAllocation {
    int sink_cell_id = -1;
    int target_cell_id = -1;
    int depression_component_id = -1;
    double target_area_km2 = 0.0;
    double routing_base_elevation_m = 0.0;
    double spill_elevation_m = 0.0;
    double prior_local_deposition_volume_km3 = 0.0;
    double accommodation_before_allocation_km3 = 0.0;
    double accommodation_deposition_volume_km3 = 0.0;
    double excess_aggradation_volume_km3 = 0.0;
    double total_deposition_volume_km3 = 0.0;
};

struct FluvialSedimentRoutingStage {
    int id = 0;
    int feedback_stage_id = 0;
    int erosion_iteration = 0;
    int active_cell_step_count = 0;
    int routed_edge_count = 0;
    int land_terminal_count = 0;
    int marine_terminal_count = 0;
    int terminal_allocation_count = 0;
    double accumulation_scale = 1.0;
    double local_source_volume_km3 = 0.0;
    double routed_throughput_volume_km3 = 0.0;
    double capacity_deposition_volume_km3 = 0.0;
    double depression_fill_deposition_volume_km3 = 0.0;
    double lake_trap_deposition_volume_km3 = 0.0;
    double terminal_land_deposition_volume_km3 = 0.0;
    double marine_deposition_volume_km3 = 0.0;
    double terminal_export_volume_km3 = 0.0;
    double mass_balance_residual_km3 = 0.0;
    double alluvium_entrainment_volume_km3 = 0.0;
    double bedrock_erosion_volume_km3 = 0.0;
    std::vector<FluvialSedimentRoutingCellStep> cell_steps;
    std::vector<FluvialSedimentTerminalAllocation> terminal_allocations;
};

struct HillslopeSedimentTransportEdge {
    int id = 0;
    int mesh_edge_cell_a_id = -1;
    int mesh_edge_cell_b_id = -1;
    int source_cell_id = -1;
    int target_cell_id = -1;
    int source_lithology = 0;
    int source_neighbor_count = 0;
    bool target_is_water = false;
    bool target_is_lake = false;
    double source_area_km2 = 0.0;
    double target_area_km2 = 0.0;
    double source_elevation_m = 0.0;
    double target_elevation_m = 0.0;
    double elevation_drop_m = 0.0;
    double source_lithology_resistance = 1.0;
    double effective_diffusivity = 0.0;
    double source_production_depth_m = 0.0;
    double target_deposition_depth_m = 0.0;
    double transfer_volume_km3 = 0.0;
    double mass_balance_residual_km3 = 0.0;
};

struct HillslopeSedimentTransportInputCell {
    int cell_id = -1;
    int lithology = 0;
    bool is_water = false;
    bool is_lake = false;
    double elevation_m = 0.0;
    double sediment_thickness_m = 0.0;
};

struct HillslopeSedimentTransportStage {
    int id = 0;
    int feedback_stage_id = 0;
    int erosion_iteration = 0;
    int transport_edge_count = 0;
    int source_cell_count = 0;
    int target_cell_count = 0;
    int land_to_land_edge_count = 0;
    int land_to_marine_edge_count = 0;
    double production_volume_km3 = 0.0;
    double deposition_volume_km3 = 0.0;
    double mass_balance_residual_km3 = 0.0;
    double alluvium_entrainment_volume_km3 = 0.0;
    double bedrock_erosion_volume_km3 = 0.0;
    double max_source_production_depth_m = 0.0;
    double max_target_deposition_depth_m = 0.0;
    double mean_effective_diffusivity = 0.0;
    std::vector<HillslopeSedimentTransportInputCell> input_cells;
    std::vector<HillslopeSedimentTransportEdge> edges;
};

struct GlacialSedimentTransportInputCell {
    int cell_id = -1;
    int glacier_flow_to_cell_id = -1;
    bool is_water = false;
    double elevation_m = 0.0;
    double ice_thickness_m = 0.0;
    double glacial_erosion_m = 0.0;
    double sediment_thickness_m = 0.0;
};

struct GlacialSedimentTransfer {
    int id = 0;
    int source_cell_id = -1;
    int target_cell_id = -1;
    bool target_is_water = false;
    double source_area_km2 = 0.0;
    double target_area_km2 = 0.0;
    double source_elevation_m = 0.0;
    double target_elevation_m = 0.0;
    double elevation_drop_m = 0.0;
    double source_ice_thickness_m = 0.0;
    double source_glacial_erosion_m = 0.0;
    double source_production_depth_m = 0.0;
    double target_deposition_depth_m = 0.0;
    double transfer_volume_km3 = 0.0;
    double mass_balance_residual_km3 = 0.0;
};

struct GlacialSedimentTransportStage {
    int id = 0;
    int feedback_stage_id = 0;
    int transfer_count = 0;
    int source_cell_count = 0;
    int target_cell_count = 0;
    int land_target_transfer_count = 0;
    int marine_target_transfer_count = 0;
    double production_volume_km3 = 0.0;
    double deposition_volume_km3 = 0.0;
    double mass_balance_residual_km3 = 0.0;
    double terrain_volume_change_residual_km3 = 0.0;
    double alluvium_entrainment_volume_km3 = 0.0;
    double bedrock_erosion_volume_km3 = 0.0;
    double max_source_production_depth_m = 0.0;
    double max_target_deposition_depth_m = 0.0;
    std::vector<GlacialSedimentTransportInputCell> input_cells;
    std::vector<GlacialSedimentTransfer> transfers;
    std::vector<double> post_transport_elevation_m_by_cell;
};

struct EarthSystemFeedbackStep {
    int id = 0;
    int erosion_iteration = -1;
    std::string stage;
    bool sea_level_recomputed = false;
    bool climate_recomputed = false;
    bool hydrologic_water_budget_recomputed = false;
    bool hydrology_recomputed = false;
    bool erosion_applied = false;
    bool cryosphere_applied = false;
    bool plate_motion_applied = false;
    bool crust_transport_applied = false;
    bool crust_evolution_applied = false;
    int sea_level_recompute_count = 0;
    int climate_recompute_count = 0;
    int hydrologic_water_budget_recompute_count = 0;
    int hydrology_recompute_count = 0;
    int numeric_depression_fill_pass_count = 0;
    int numeric_depression_fill_event_count = 0;
    int numeric_depression_fill_cell_application_count = 0;
    int numeric_depression_filled_unique_cell_count = 0;
    int numeric_depression_correction_event_count = 0;
    int numeric_depression_breach_selected_event_count = 0;
    int numeric_depression_breach_excavation_cell_application_count = 0;
    int numeric_depression_breach_deposition_cell_application_count = 0;
    int numeric_depression_temporary_lake_event_count = 0;
    int numeric_depression_temporary_lake_cell_application_count = 0;
    int numeric_depression_temporary_lake_unique_cell_count = 0;
    int fluvial_sediment_active_cell_step_count = 0;
    int fluvial_sediment_routed_edge_count = 0;
    int fluvial_sediment_land_terminal_count = 0;
    int fluvial_sediment_marine_terminal_count = 0;
    int fluvial_sediment_terminal_allocation_count = 0;
    int hillslope_sediment_transport_edge_count = 0;
    int hillslope_sediment_source_cell_count = 0;
    int hillslope_sediment_target_cell_count = 0;
    int hillslope_sediment_land_to_land_edge_count = 0;
    int hillslope_sediment_land_to_marine_edge_count = 0;
    int glacial_sediment_transfer_count = 0;
    int glacial_sediment_source_cell_count = 0;
    int glacial_sediment_target_cell_count = 0;
    int glacial_sediment_land_target_transfer_count = 0;
    int glacial_sediment_marine_target_transfer_count = 0;
    int plate_motion_history_id = 0;
    int cell_count = 0;
    int land_cell_count = 0;
    int water_cell_count = 0;
    int river_cell_count = 0;
    double sea_level_adjustment_m = 0.0;
    double numeric_depression_fill_area_km2 = 0.0;
    double numeric_depression_fill_volume_km3 = 0.0;
    double max_numeric_depression_fill_depth_m = 0.0;
    double numeric_depression_breach_excavation_volume_km3 = 0.0;
    double numeric_depression_breach_deposition_volume_km3 = 0.0;
    double numeric_depression_correction_mass_balance_residual_km3 = 0.0;
    double numeric_depression_temporary_lake_candidate_area_km2 = 0.0;
    double numeric_depression_temporary_lake_candidate_volume_km3 = 0.0;
    double max_numeric_depression_temporary_lake_depth_m = 0.0;
    double fluvial_sediment_local_source_volume_km3 = 0.0;
    double fluvial_sediment_routed_throughput_volume_km3 = 0.0;
    double fluvial_sediment_capacity_deposition_volume_km3 = 0.0;
    double fluvial_sediment_depression_fill_deposition_volume_km3 = 0.0;
    double fluvial_sediment_lake_trap_deposition_volume_km3 = 0.0;
    double fluvial_sediment_terminal_land_deposition_volume_km3 = 0.0;
    double fluvial_sediment_marine_deposition_volume_km3 = 0.0;
    double fluvial_sediment_terminal_export_volume_km3 = 0.0;
    double fluvial_sediment_mass_balance_residual_km3 = 0.0;
    double hillslope_sediment_production_volume_km3 = 0.0;
    double hillslope_sediment_deposition_volume_km3 = 0.0;
    double hillslope_sediment_mass_balance_residual_km3 = 0.0;
    double max_hillslope_sediment_source_production_depth_m = 0.0;
    double max_hillslope_sediment_target_deposition_depth_m = 0.0;
    double mean_hillslope_effective_diffusivity = 0.0;
    double glacial_sediment_production_volume_km3 = 0.0;
    double glacial_sediment_deposition_volume_km3 = 0.0;
    double glacial_sediment_mass_balance_residual_km3 = 0.0;
    double glacial_sediment_terrain_volume_change_residual_km3 = 0.0;
    double max_glacial_sediment_source_production_depth_m = 0.0;
    double max_glacial_sediment_target_deposition_depth_m = 0.0;
    double sediment_alluvium_entrainment_volume_km3 = 0.0;
    double sediment_bedrock_erosion_volume_km3 = 0.0;
    double sediment_inventory_volume_km3 = 0.0;
    double sediment_source_partition_residual_km3 = 0.0;
    double sediment_inventory_mass_balance_residual_km3 = 0.0;
    double surface_area_km2 = 0.0;
    double ocean_area_km2 = 0.0;
    double ocean_volume_km3 = 0.0;
    double ocean_fraction = 0.0;
    double mean_elevation_m = 0.0;
    double mean_land_elevation_m = 0.0;
    double min_elevation_m = 0.0;
    double max_elevation_m = 0.0;
    double mean_temperature_c = 0.0;
    double mean_precipitation_mm_y = 0.0;
    double mean_runoff_mm_y = 0.0;
    double hydrologic_land_precipitation_volume_km3_y = 0.0;
    double hydrologic_actual_evapotranspiration_volume_km3_y = 0.0;
    double hydrologic_infiltration_volume_km3_y = 0.0;
    double hydrologic_runoff_volume_km3_y = 0.0;
    double hydrologic_water_budget_residual_km3_y = 0.0;
    double max_abs_hydrologic_water_budget_cell_residual_mm_y = 0.0;
    double mean_erosion_rate_m_per_step = 0.0;
    double mean_sediment_thickness_m = 0.0;
    double mean_cumulative_sediment_production_m = 0.0;
    double mean_cumulative_sediment_deposition_m = 0.0;
    double mean_cumulative_sediment_export_m = 0.0;
    double cumulative_sediment_production_volume_km3 = 0.0;
    double cumulative_sediment_deposition_volume_km3 = 0.0;
    double cumulative_sediment_export_volume_km3 = 0.0;
    double mean_abs_elevation_change_m_from_previous_stage = 0.0;
    double mean_abs_temperature_change_c_from_previous_stage = 0.0;
    double mean_abs_precipitation_change_mm_y_from_previous_stage = 0.0;
    double mean_abs_runoff_change_mm_y_from_previous_stage = 0.0;
};

struct PlateKinematicSnapshot {
    int plate_id = 0;
    Vec3 center;
    double step_rotation_deg = 0.0;
    double cumulative_rotation_deg = 0.0;
    int cell_count = 0;
    double area_km2 = 0.0;
};

struct CrustMotionDiagnostics {
    std::vector<int> source_cell_ids;
    std::vector<double> transport_distance_km_by_cell;
    std::vector<double> age_transport_change_ma_by_cell;
    std::vector<double> thickness_transport_change_km_by_cell;
    std::vector<double> density_transport_change_by_cell;
    std::vector<double> age_process_change_ma_by_cell;
    std::vector<double> thickness_process_change_km_by_cell;
    std::vector<double> density_process_change_by_cell;
    std::vector<int> aged_oceanic_cell_ids;
    std::vector<int> rejuvenated_oceanic_cell_ids;
    std::vector<int> subducted_oceanic_cell_ids;
};

struct PlateMotionStep {
    int id = 0;
    int erosion_iteration = -1;
    std::string stage;
    int cell_count = 0;
    int plate_count = 0;
    int reassigned_cell_count = 0;
    int plate_boundary_cell_count = 0;
    int plate_boundary_edge_count = 0;
    int accreted_terrane_cell_count = 0;
    int crust_source_remap_cell_count = 0;
    int unique_crust_source_cell_count = 0;
    int crust_source_reuse_count = 0;
    int aged_oceanic_cell_count = 0;
    int rejuvenated_oceanic_cell_count = 0;
    int subducted_oceanic_cell_count = 0;
    double reassigned_cell_fraction = 0.0;
    double mean_plate_rotation_deg = 0.0;
    double max_plate_rotation_deg = 0.0;
    double mean_crust_transport_distance_km = 0.0;
    double max_crust_transport_distance_km = 0.0;
    double mean_abs_crust_age_change_ma = 0.0;
    double mean_abs_crust_thickness_change_km = 0.0;
    double mean_abs_crust_density_change = 0.0;
    double mean_abs_crust_age_transport_change_ma = 0.0;
    double mean_abs_crust_thickness_transport_change_km = 0.0;
    double mean_abs_crust_density_transport_change = 0.0;
    double mean_abs_crust_age_process_change_ma = 0.0;
    double mean_abs_crust_thickness_process_change_km = 0.0;
    double mean_abs_crust_density_process_change = 0.0;
    double mean_tectonic_elevation_change_m = 0.0;
    double mean_abs_tectonic_elevation_change_m = 0.0;
    double max_abs_tectonic_elevation_change_m = 0.0;
    std::vector<int> cell_plate_ids;
    std::vector<int> crust_source_cell_ids;
    std::vector<int> crust_type_by_cell;
    std::vector<int> lithology_by_cell;
    std::vector<double> crust_transport_distance_km_by_cell;
    std::vector<double> crust_age_change_ma_by_cell;
    std::vector<double> crust_thickness_change_km_by_cell;
    std::vector<double> crust_density_change_by_cell;
    std::vector<double> crust_age_transport_change_ma_by_cell;
    std::vector<double> crust_thickness_transport_change_km_by_cell;
    std::vector<double> crust_density_transport_change_by_cell;
    std::vector<double> crust_age_process_change_ma_by_cell;
    std::vector<double> crust_thickness_process_change_km_by_cell;
    std::vector<double> crust_density_process_change_by_cell;
    std::vector<double> tectonic_elevation_change_m_by_cell;
    std::vector<int> aged_oceanic_cell_ids;
    std::vector<int> rejuvenated_oceanic_cell_ids;
    std::vector<int> subducted_oceanic_cell_ids;
    std::vector<PlateKinematicSnapshot> plates;
};

}  // namespace magic_geo::detail
