"""Per-cell CSV export."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import csv
import json

from ..public_estimate_display import CELL_SUPPORT, nullable_kind, display_contract


def write_cells_csv(path: Path, world: dict[str, Any]) -> None:
    contract = display_contract(world)
    cells = world.get("cells", [])
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "id",
        "lat_deg",
        "lon_deg",
        "mesh_lod_face",
        "mesh_lod_finest_tile_id",
        "boundary_vertex_count",
        "cell_boundary_perimeter_km",
        "cell_polygon_area_km2",
        "cell_polygon_area_error_fraction",
        "cell_geometry_quality",
        "cell_edge_count",
        "mean_neighbor_edge_length_km",
        "max_neighbor_edge_length_km",
        "mean_neighbor_boundary_segment_length_km",
        "max_neighbor_boundary_segment_length_km",
        "mean_neighbor_boundary_segment_mismatch_km",
        "mean_neighbor_boundary_segment_quality",
        "tectonic_neighbor_edge_count",
        "land_water_neighbor_edge_count",
        "biome_transition_neighbor_edge_count",
        "political_region_id",
        "culture_region_id",
        "language_region_id",
        "plate_id",
        "crust_type",
        "boundary_type",
        "collision_zone_id",
        "subduction_zone_id",
        "rift_zone_id",
        "dominant_tectonic_zone_type",
        "tectonic_zone_strength",
        "lithology",
        "crust_age_ma",
        "crust_thickness_km",
        "crust_density",
        "initial_isostatic_elevation_m",
        "initial_ridge_uplift_m",
        "initial_orogenic_uplift_m",
        "initial_volcanic_uplift_m",
        "initial_trench_subsidence_m",
        "initial_rift_subsidence_m",
        "initial_transform_fault_relief_m",
        "initial_secondary_roughness_m",
        "initial_elevation_m",
        "tectonic_uplift_rate_m_per_step",
        "volcanic_potential_index",
        "elevation_m",
        "water_depth_m",
        "water_body_type",
        "landmass_id",
        "island_class",
        "marine_region_id",
        "marine_chokepoint_id",
        "river_navigability_index",
        "coastal_navigability_index",
        "harbor_suitability_index",
        "transport_chokepoint_index",
        "navigability_index",
        "navigability_class",
        "navigable_waterway_id",
        "protected_bay_index",
        "river_mouth_port_index",
        "strait_access_index",
        "port_suitability_index",
        "port_site_type",
        "port_site_id",
        "mountain_pass_route_index",
        "river_valley_route_index",
        "coastal_route_index",
        "oasis_route_index",
        "route_corridor_index",
        "route_corridor_type",
        "route_corridor_id",
        "reef_growth_index",
        "reef_sediment_stress_index",
        "reef_wave_exposure_index",
        "reef_island_support_index",
        "reef_bleaching_risk_index",
        "reef_type",
        "reef_system_id",
        "temperature_c",
        "precipitation_mm_y",
        "wind_east",
        "wind_north",
        "mean_seasonal_wind_speed",
        "seasonal_wind_reversal_index",
        "atmospheric_cell",
        "surface_pressure_anomaly_hpa",
        "vertical_velocity_index",
        "wind_divergence_index",
        "ocean_current_east",
        "ocean_current_north",
        "ocean_current_temperature_c",
        "ocean_current_moisture_factor",
        "humidity_transport_index",
        "upwind_ocean_fetch_km",
        "advected_moisture_factor",
        "orographic_factor",
        "rain_shadow_factor",
        "vapor_evaporation_mm_y",
        "moisture_convergence_mm_y",
        "orographic_rainout_mm_y",
        "precipitation_recycling_fraction",
        "vapor_deficit_mm_y",
        "vapor_budget_residual_mm_y",
        "seasonal_precipitation_range_mm",
        "seasonal_aridity_index",
        "cell_monsoon_index",
        "seasonal_humidity_regime",
        "climate_class",
        "top_of_atmosphere_insolation_w_m2",
        "surface_albedo_index",
        "surface_albedo_regime",
        "absorbed_shortwave_w_m2",
        "outgoing_longwave_w_m2",
        "greenhouse_trapping_w_m2",
        "net_radiative_balance_w_m2",
        "no_greenhouse_equilibrium_temperature_c",
        "radiative_equilibrium_temperature_c",
        "energy_balance_residual_c",
        "climate_energy_stress_index",
        "runoff_mm_y",
        "flow_to",
        "equal_filled_raw_downhill_rerouted",
        "spill_to",
        "depression_component_id",
        "depression_sink_cell_id",
        "lake_basin_id",
        "depression_policy",
        "flow_accumulation",
        "filled_elevation_m",
        "depression_depth_m",
        "spill_elevation_m",
        "lake_fill_fraction",
        "basin_id",
        "is_river",
        "is_lake",
        "is_closed_basin",
        "lake_overflows",
        "overflow_channel_active",
        "overflow_channel_incision_m",
        "overflow_channel_sediment_evacuated_km3",
        "overflow_channel_avulsion_risk",
        "river_capture_risk",
        "river_capture_target_cell_id",
        "river_capture_target_basin_id",
        "river_capture_divide_relief_m",
        "river_capture_target_distance_km",
        "river_avulsion_risk",
        "river_network_instability_index",
        "erosion_rate",
        "sediment_thickness_m",
        "sediment_deposition_m",
        "sediment_export_m",
        "sediment_net_budget_m",
        "sediment_routing_load_m",
        "sediment_routing_deposition_m",
        "sediment_routing_export_m",
        "sediment_routing_path_count",
        "ice_thickness_m",
        "ice_sheet_id",
        "glacier_flow_to",
        "ice_surface_mass_balance_m_y",
        "basal_sliding_index",
        "ice_velocity_m_y",
        "glacial_erosion_m",
        "moraine_deposition_m",
        "deglaciation_age_ka",
        "ice_flowline_flux_km3_y",
        "ice_flowline_driving_stress_kpa",
        "ice_flowline_strain_heating_index",
        "ice_flowline_path_count",
        "permafrost_extent_index",
        "active_layer_depth_m",
        "ground_ice_content_index",
        "permafrost_class",
        "permafrost_region_id",
        "landform",
        "soil_type",
        "soil_texture_class",
        "soil_drainage_index",
        "soil_moisture_index",
        "soil_ph",
        "soil_organic_matter_fraction",
        "soil_salinity_index",
        "soil_erodibility_index",
        "soil_profile_development_index",
        "soil_profile_id",
        "soil_horizon_count",
        "biome",
        "potential_evapotranspiration_mm_y",
        "climatic_water_deficit_mm_y",
        "climatic_water_surplus_mm_y",
        "growing_season_months",
        "frost_months",
        "dry_season_months",
        "wet_season_months",
        "fire_frequency_index",
        "biome_confidence_index",
        "ecotone_index",
        "biome_transition_zone",
        "biome_ecotone_type",
        "biome_ecotone_confidence",
        "biome_ecotone_region_id",
        "groundwater_recharge_mm_y",
        "groundwater_recharge_km3_y",
        "aquifer_storage_index",
        "aquifer_quality_index",
        "aquifer_productivity_index",
        "aquifer_extraction_risk_index",
        "aquifer_class",
        "aquifer_system_id",
        "karst_potential_index",
        "cave_development_index",
        "subterranean_drainage_fraction",
        "karst_system_id",
        "primary_productivity_index",
        "vegetation_biomass_index",
        "species_richness_index",
        "wildfire_spread_risk_index",
        "ecosystem_disturbance_pressure_index",
        "vegetation_succession_stage",
        "vegetation_recovery_years",
        "forest_growth_index",
        "fishery_productivity_index",
        "resource",
        "agricultural_potential_index",
        "mining_potential_index",
        "agricultural_zone_id",
        "mining_zone_id",
        "natural_frontier_index",
        "natural_frontier_type",
        "natural_frontier_id",
        "settlement_score",
        "continental_shelf_id",
        "distance_to_marine_water_km",
        "continentality_index",
        "oceanic_humidity_availability_index",
        "marine_influence_class",
        "climate_continentality_region_id",
        "actual_evapotranspiration_mm_y",
        "infiltration_capacity_index",
        "infiltration_mm_y",
        "hydrologic_water_balance_mm_y",
        "water_budget_runoff_mm_y",
        "runoff_budget_residual_mm_y",
        "runoff_budget_consistency_index",
        "hydrologic_deficit_mm_y",
        "runoff_generation_fraction",
        "hydrologic_budget_class",
        "hydrologic_budget_region_id",
        "wetland_extent_index",
        "wetland_hydrology_index",
        "wetland_soil_saturation_index",
        "wetland_ecotone_index",
        "wetland_connectivity_index",
        "wetland_coastal_flag",
        "wetland_system_type",
        "wetland_system_id",
        "glacial_landform_index",
        "glacial_erosion_intensity_index",
        "glacial_deposition_index",
        "glacial_meltwater_index",
        "glacial_landform_type",
        "glacial_landform_system_id",
        "seasonal_insolation_range_w_m2",
        "orbital_insolation_variability_index",
        "peak_seasonal_insolation_w_m2",
        "low_seasonal_insolation_w_m2",
        "fault_slip_rate_index",
        "seismic_hazard_index",
        "earthquake_recurrence_interval_y",
        "fault_system_id",
        "groundwater_hydraulic_head_m",
        "groundwater_gradient_index",
        "groundwater_lateral_flow_km3_y",
        "groundwater_discharge_mm_y",
        "groundwater_discharge_km3_y",
        "groundwater_flow_to_cell_id",
        "spring_discharge_index",
        "baseflow_support_index",
        "groundwater_flow_regime",
        "groundwater_flow_system_id",
        "river_channel_width_m",
        "river_channel_depth_m",
        "bankfull_discharge_m3_s",
        "channel_slope_index",
        "stream_power_index",
        "floodplain_connectivity_index",
        "channel_morphology_class",
        "river_channel_system_id",
        "hydraulic_radius_m",
        "flow_velocity_m_s",
        "froude_number",
        "bed_shear_stress_pa",
        "manning_roughness_n",
        "channel_capacity_index",
        "hydraulic_navigability_index",
        "hydraulic_flow_regime",
        "river_hydraulic_reach_id",
        "dominant_species_guild",
        "species_habitat_suitability_index",
        "species_endemism_index",
        "species_range_fragmentation_index",
        "species_composition_confidence_index",
        "species_guild_richness_count",
        "species_range_record_ids",
        "wildfire_ignition_potential_index",
        "wildfire_fuel_continuity_index",
        "wildfire_wind_alignment_index",
        "wildfire_firebreak_index",
        "wildfire_disturbance_regime",
        "wildfire_spread_history_ids",
        "petroleum_source_rock_index",
        "petroleum_maturation_index",
        "petroleum_migration_path_index",
        "petroleum_trap_integrity_index",
        "petroleum_accumulation_index",
        "petroleum_system_id",
        "ore_genesis_potential_index",
        "hydrothermal_alteration_index",
        "metallogenic_fertility_index",
        "ore_structural_control_index",
        "placer_concentration_index",
        "ore_genesis_system_id",
        "healpix_like_nside",
        "healpix_like_ring",
        "healpix_like_lon_bin",
        "healpix_like_pixel_id",
        "healpix_like_pixel_code",
        "s2_like_face",
        "s2_like_face_id",
        "s2_like_cell_level",
        "s2_like_x",
        "s2_like_y",
        "s2_like_cell_id",
        "s2_like_token",
        "ocean_current_speed_index",
        "ocean_current_poleward_index",
        "ocean_heat_transport_index",
        "ocean_current_transport_alignment",
        "ocean_current_transport_target_cell_id",
        "ocean_current_transport_distance_km",
        "ocean_current_convergence_index",
        "ocean_upwelling_index",
        "ocean_current_regime",
        "ocean_current_system_id",
        "initial_plate_id",
        "plate_assignment_change_count",
        "last_plate_assignment_change_iteration",
        "cumulative_tectonic_elevation_change_m",
        "oceanic_crust_aging_event_count",
        "oceanic_crust_rejuvenation_event_count",
        "oceanic_crust_subduction_event_count",
        "cumulative_crust_transport_distance_km",
        "hydrologic_surface_elevation_m",
        "hydrologic_flow_drop_m",
        "hydrologic_flow_slope",
        "hydrologic_surface_conditioned",
        "cumulative_numeric_depression_breach_excavation_m",
        "cumulative_numeric_depression_breach_deposition_m",
        "numeric_depression_breach_event_count",
        "glacial_sediment_deposition_m",
        "numeric_depression_temporary_lake_event_count",
        "fluvial_sediment_local_source_m",
        "fluvial_sediment_routed_incoming_m",
        "fluvial_sediment_routed_outgoing_m",
        "fluvial_sediment_local_deposition_m",
        "fluvial_sediment_terminal_land_deposition_m",
        "fluvial_sediment_marine_deposition_m",
        "fluvial_sediment_depression_fill_m",
        "fluvial_sediment_terminal_export_m",
        "fluvial_sediment_terminal_capture_volume_km3",
        "fluvial_sediment_routing_event_count",
        "hillslope_sediment_production_m",
        "hillslope_sediment_deposition_m",
        "hillslope_sediment_net_m",
        "hillslope_sediment_outgoing_edge_count",
        "hillslope_sediment_incoming_edge_count",
        "glacial_sediment_production_m",
        "glacial_sediment_net_m",
        "glacial_sediment_outgoing_transfer_count",
        "glacial_sediment_incoming_transfer_count",
        "sediment_alluvium_entrainment_m",
        "sediment_bedrock_erosion_m",
        "hydrologic_potential_evapotranspiration_mm_y",
        "groundwater_recharge_source_infiltration_mm_y",
        "groundwater_recharge_fraction",
        "vadose_zone_retention_mm_y",
        "vadose_zone_retention_km3_y",
        "groundwater_recharge_mass_balance_residual_mm_y",
        "groundwater_lateral_inflow_km3_y",
        "groundwater_available_volume_km3_y",
        "groundwater_internal_lateral_outflow_km3_y",
        "groundwater_retained_storage_km3_y",
        "groundwater_flow_mass_balance_residual_km3_y",
        "thermal_subsidence_target_m",
        "aquatic_climate_proxy_applicable",
        "aquatic_primary_climate_supported",
        "fishery_climate_supported",
        "fishery_productivity_supported",
        "species_terrestrial_habitat_eligible",
        "species_freshwater_habitat_eligible",
        "species_marine_habitat_eligible",
        "species_freshwater_fish_score_supported",
        "species_marine_fish_score_supported",
        "species_freshwater_fishery_input_mode",
        "effective_toa_albedo",
        "effective_longwave_emissivity",
        "annual_absorbed_shortwave_w_m2",
        "annual_emitted_longwave_w_m2",
        "annual_net_radiative_flux_w_m2",
        "annual_horizontal_heat_convergence_w_m2",
        "annual_net_heating_w_m2",
        "annual_heat_storage_tendency_w_m2",
        "annual_energy_balance_residual_w_m2",
        "annual_mean_abs_energy_balance_residual_w_m2",
        "annual_mean_energy_balance_numerical_allowance_w_m2",
        "terrestrial_primary_climate_supported",
        "primary_productivity_supported",
        "vegetation_biomass_supported",
        "forest_growth_supported",
        "vegetation_succession_supported",
        "species_richness_supported",
        "ecosystem_wildfire_spread_risk_supported",
        "ecosystem_disturbance_pressure_supported",
        "vegetation_recovery_supported",
        "species_canopy_tree_score_supported",
        "species_grassland_grazer_score_supported",
        "species_desert_specialist_score_supported",
        "species_alpine_tundra_specialist_score_supported",
        "species_large_predator_score_supported",
        "species_wetland_amphibian_score_supported",
        "species_reef_builder_score_supported",
        "species_mangrove_coastal_bird_score_supported",
        "species_composition_confidence_supported",
        "species_endemism_supported",
        "species_record_descriptors_supported",
        "species_guild_scores",
        "species_applicable_guild_count",
        "species_supported_guild_count",
        "species_composition_status",
        "wildfire_fuel_continuity_supported",
        "wildfire_firebreak_supported",
        "wildfire_ignition_potential_supported",
        "aquifer_natural_limitation_index",
        "agricultural_habitat_applicable",
        "agricultural_climate_supported",
        "agricultural_potential_supported",
        "mining_surface_applicable",
    ]
    additions = ["settlement_climate_temperature_c", "settlement_climate_supported", "is_water", "is_lake",
                 "harbor_site_applicable", *CELL_SUPPORT.values()]
    fieldnames.extend(key for key in dict.fromkeys(additions) if key not in fieldnames)
    for key in ("grounded_ice_surface_applicable", "grounded_ice_diagnostic_thickness_m"):
        if any(key in cell for cell in cells):
            fieldnames.append(key)
    if any("marine_distance_status" in cell for cell in cells):
        fieldnames.append("marine_distance_status")
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for cell in cells:
            row = cell
            if isinstance(cell.get("species_guild_scores"), dict):
                row = {**cell, "species_guild_scores": json.dumps(
                    cell["species_guild_scores"], sort_keys=True, separators=(",", ":"), allow_nan=False,
                )}
            writer.writerow(row)

    def column_type(key):
        if key == "grounded_ice_diagnostic_thickness_m":
            return "number"
        if key == "distance_to_marine_water_km" and "marine_distance_status" in fieldnames:
            return "number"
        if key in set(CELL_SUPPORT.values()) | {"is_water", "is_lake", "harbor_site_applicable", "grounded_ice_surface_applicable"}:
            return "boolean"
        kinds = {type(cell[key]) for cell in cells if cell.get(key) is not None}
        if kinds and kinds <= {int, float}:
            return "number" if float in kinds else "integer"
        if kinds == {bool}: return "boolean"
        if kinds == {str}: return "string"
        if key == "species_guild_scores": return "json_object"
        known = nullable_kind(cells, key)
        return {"int": "integer", "float": "number", "str": "string"}.get(known, "legacy_text_or_undeclared")
    schema = {
        "schema": "magic_geo_cell_csv_estimate_profile_v1",
        "scope": world.get("generation_scope", "full"),
        "columns": fieldnames,
        "column_types": {key: column_type(key) for key in fieldnames},
        "availability_fields": {key: value for key, value in CELL_SUPPORT.items() if key in fieldnames},
        "boolean_lexical_values": {"true": "True", "false": "False"},
        "empty_field_policy": "null_or_absent; consult declared model and availability fields; raw JSON retains exact key presence",
        "zero_policy": "numeric_zero_is_preserved; settlement dry sentinel requires its climate support and water selectors",
        "coverage": "cell_columns_only; linked world records require JSON or record exports",
        "declarations": contract,
    }
    if "marine_distance_status" in fieldnames:
        schema["marine_distance"] = {
            "distance_field": "distance_to_marine_water_km",
            "status_field": "marine_distance_status",
            "status_values": ["reachable_marine", "no_marine_source"],
            "null_meaning": "no_marine_source",
            "zero_meaning": "defined_zero_distance_to_a_marine_source",
            "legacy_absent_status": "undeclared; raw distance retained",
        }
    if "grounded_ice_surface_applicable" in fieldnames:
        schema["grounded_ice_applicability"] = {
            "field": "grounded_ice_surface_applicable",
            "false_meaning": "grounded_ice_process_inapplicable_not_absence_of_lake_or_sea_ice",
            "raw_values": "numeric_zero_and_glacier_flow_to_minus_one_are_retained_not_missing_estimates",
            "association": "ice_sheet_id_may_link_glacial_context_not_active_ice_membership",
            "active_thickness_field": "grounded_ice_diagnostic_thickness_m",
            "active_thickness_precision": "roundtrip_binary64_decimal_v1",
            "active_membership": "applicable_and_raw_diagnostic_thickness_strictly_above_25_m",
        }
    path.with_suffix(path.suffix + ".schema.json").write_text(json.dumps(schema, indent=2, sort_keys=True, allow_nan=False) + "\n", encoding="utf-8")
