"""Causal-replay validation for the population, conflict, and dynasty models.

``validate_civilization_geography_replay`` recomputes every population region,
conflict, and dynasty record from the raw cell/region/culture/event inputs and
compares them field by field. The canonical controls use generated worlds;
explicitly labeled stage tests exercise controlled downstream inputs separately.

Every failure case below therefore follows the same three-legged shape, applied
by :meth:`_assert_only_the_tamper_fails`:

1. the untampered canonical world replays clean,
2. one tamper makes the validator return the single fixed failure string,
3. undoing that one tamper makes the very same payload replay clean again.

Leg 3 is what keeps these tests honest: a tamper that was never the cause of the
failure (or an assertion that could not fail) makes leg 1 or leg 3 blow up.

Regime note: at 128 cells the world has one political region, one culture, one
population region, one dynasty, and — because ``borders`` is empty — zero
conflicts, so the canonical world alone cannot reach the conflict record builder
or a second dynasty generation. Three further payloads reach those:

* ``mid_512`` (canonical, two regions) carries one real conflict
  record, so its fields can be tampered with;
* fabricated border segments appended to the 128-cell world drive the candidate
  filters and the conflict chronology without disturbing the population replay
  (borders are not a population input, which is what keeps the replay reaching
  the conflict builder at all);
* two retained one-off current-model configurations — :data:`MULTI_DYNASTY_WORLD`
  and :data:`RIVAL_REGION_WORLD` — clear the model's 0.36 succession threshold,
  giving their regions a second dynasty generation, collapse reasons and lineage
  links. Their physical worlds remain unmodified; a separate dynasty-stage
  route-removal control preserves trade-decline priority coverage.
"""

from __future__ import annotations

from typing import Any
from unittest import TestCase

from support import worlds

from magic_geo.api import generate_world
from magic_geo.civilization_geography_validation import (
    _dynasty_matches,
    _dynasty_records,
    validate_civilization_geography_replay,
)

#: The single message the validator returns for any mismatch.
FAILURE = "population, conflict, or dynasty model causal replay invalid"

CANONICAL_WORLD = "replay_128"

#: The smallest canonical world that draws political borders, and therefore the
#: one used here to tamper a conflict record.
BORDERED_WORLD = "mid_512"

#: One-off configurations (``mesh.cell_count``, ``run.seed``) generated by this
#: file alone. ``MULTI_DYNASTY_WORLD`` gives both its regions a second dynasty
#: generation; ``RIVAL_REGION_WORLD`` has three regions, which puts a region in two
#: conflicts at once and pushes its conflict pressure past 0.45.
# Both regional lines still split under current seasonal climate. Their routes
# now keep both first-generation collapse reasons in the succession-crisis branch.
MULTI_DYNASTY_WORLD = (1280, 3015)
RIVAL_REGION_WORLD = (2048, 1234)

#: Model identities published in ``README.md`` for these three subsystems.
POPULATION_REGION_MODEL = "causal_area_weighted_capacity_occupancy_population_regions_v1"
CONFLICT_MODEL = "causal_border_pair_pressure_trade_conflict_selection_v1"
DYNASTY_MODEL = "causal_foundation_continuity_pressure_dynasty_lineages_v1"

_MISSING = object()

#: Generated at most once per process, like :mod:`support.worlds` does for the
#: canonical set. Callers must not mutate the shared payload.
_ONE_OFF_WORLDS: dict[tuple[int, int], dict[str, Any]] = {}


def _one_off_world(config: tuple[int, int]) -> dict[str, Any]:
    """The shared one-off world for ``(cell_count, seed)``; never mutate it."""
    if config not in _ONE_OFF_WORLDS:
        cell_count, seed = config
        _ONE_OFF_WORLDS[config] = generate_world(
            worlds.build_config(**{"mesh.cell_count": cell_count, "run.seed": seed})
        )
    return _ONE_OFF_WORLDS[config]


def _with_private_records(world: dict[str, Any], family: str) -> dict[str, Any]:
    """A payload sharing ``world`` except for private copies of ``family``.

    Deep-copying a 2048-cell world for every tamper costs more than generating
    it, and these tampers only ever rewrite a top-level field of one record, so
    copying that one family is enough to leave the shared world untouched.
    """
    payload = dict(world)
    payload[family] = [dict(record) for record in world[family]]
    return payload


class CivilizationGeographyReplayValidationTests(TestCase):
    def _clean_world(self) -> dict[str, Any]:
        """A private copy of the canonical world, proven clean before tampering."""
        world = worlds.cached_world(CANONICAL_WORLD)
        self.assertEqual(
            validate_civilization_geography_replay(world),
            [],
            "the untampered copy must replay clean, otherwise no tamper proves anything",
        )
        return world

    def _assert_only_the_tamper_fails(
        self,
        world: dict[str, Any],
        mapping: dict[str, Any],
        key: str,
        value: Any,
    ) -> None:
        """Set ``mapping[key] = value``, require the failure, undo, require clean."""
        original = mapping.get(key, _MISSING)
        self.assertNotEqual(
            original, value, f"{key!r} already holds {value!r}; this tamper changes nothing"
        )
        mapping[key] = value

        self.assertEqual(
            validate_civilization_geography_replay(world),
            [FAILURE],
            f"tampering {key!r} must be reported as a replay failure",
        )

        if original is _MISSING:
            del mapping[key]
        else:
            mapping[key] = original
        self.assertEqual(
            validate_civilization_geography_replay(world),
            [],
            f"undoing the {key!r} tamper must replay clean again, otherwise the "
            "failure above was not caused by that tamper",
        )

    def _assert_only_the_removal_fails(
        self, world: dict[str, Any], mapping: dict[str, Any], key: str
    ) -> None:
        """Delete ``mapping[key]``, require the failure, restore, require clean."""
        original = mapping.pop(key)

        self.assertEqual(
            validate_civilization_geography_replay(world),
            [FAILURE],
            f"a payload missing {key!r} must be reported as a replay failure",
        )

        mapping[key] = original
        self.assertEqual(
            validate_civilization_geography_replay(world),
            [],
            f"restoring {key!r} must replay clean again",
        )

    def _assert_only_the_list_tamper_fails(
        self, world: dict[str, Any], records: list[Any], mutate: Any, label: str
    ) -> None:
        """Mutate ``records`` in place, require the failure, restore, require clean."""
        original = list(records)
        mutate(records)
        self.assertNotEqual(records, original, f"{label} left the list unchanged")

        self.assertEqual(
            validate_civilization_geography_replay(world),
            [FAILURE],
            f"{label} must be reported as a replay failure",
        )

        records[:] = original
        self.assertEqual(
            validate_civilization_geography_replay(world),
            [],
            f"undoing {label} must replay clean again",
        )

    def test_canonical_world_replays_clean(self) -> None:
        world = worlds.cached_world_readonly(CANONICAL_WORLD)

        self.assertEqual(validate_civilization_geography_replay(world), [])

    def test_payload_declares_the_documented_model_identities(self) -> None:
        # The identity strings come from README.md, not from the validator, so
        # this fails if the generator ever renames a model behind the docs.
        world = worlds.cached_world_readonly(CANONICAL_WORLD)

        for key, model_id in (
            ("population_region_model", POPULATION_REGION_MODEL),
            ("conflict_model", CONFLICT_MODEL),
            ("dynasty_model", DYNASTY_MODEL),
        ):
            with self.subTest(model=key):
                self.assertEqual(world[key]["model_type"], model_id)
                self.assertEqual(world["summary"][key], model_id)
                self.assertIs(world[key]["deterministic"], True)

    def test_population_record_field_tampers_are_detected(self) -> None:
        # Every field the validator recomputes must be compared; each tamper is
        # far larger than the tolerance the validator allows for that field.
        world = self._clean_world()
        record = world["population_regions"][0]
        cases: dict[str, Any] = {
            "estimated_population": 1.0,
            "carrying_capacity": 1.0,
            "agricultural_capacity_index": 1.0,
            "water_security_index": 0.0,
            "urbanization_fraction": 0.62,
            "growth_rate_per_year": 0.018,
            "population_pressure": 1.0,
            "migration_balance": 0.5,
            "hazard_mortality_index": 0.0,
            "settlement_count": 4,
            "region_id": 1,
            "culture_region_id": -1,
            "language_region_id": 1,
        }
        for field, value in cases.items():
            with self.subTest(population_field=field):
                self._assert_only_the_tamper_fails(world, record, field, value)

    def test_dynasty_record_field_tampers_are_detected(self) -> None:
        world = self._clean_world()
        record = world["dynasties"][0]
        cases: dict[str, Any] = {
            "region_id": 1,
            "culture_region_id": -1,
            "language_region_id": 1,
            "parent_dynasty_id": 0,
            "founder_dynasty_id": -1,
            "successor_dynasty_id": 0,
            "founding_event_id": -1,
            "collapse_reason": "conflict_defeat",
            "lineage_depth": 1,
            "child_dynasty_count": 1,
            "child_dynasty_ids": [1],
            "start_year_bp": 1000.0,
            "end_year_bp": 5.0,
            "duration_years": 1000.0,
            "legitimacy_index": 0.0,
            "succession_pressure": 0.9,
            "dynastic_continuity_index": 0.0,
        }
        for field, value in cases.items():
            with self.subTest(dynasty_field=field):
                self._assert_only_the_tamper_fails(world, record, field, value)

    def test_record_ids_must_equal_their_list_index(self) -> None:
        # Every record family is index-addressed, so a renumbered first record
        # has to be rejected even though no derived value changed.
        world = self._clean_world()
        families = (
            "cells",
            "political_regions",
            "cultures",
            "population_regions",
            "dynasties",
            "historical_events",
            "trade_flows",
        )
        for family in families:
            with self.subTest(family=family):
                records = world[family]
                self.assertTrue(records, f"{family} is empty, so this tamper cannot bite")
                self.assertEqual(records[0]["id"], 0, f"{family}[0] must start numbered 0")
                self._assert_only_the_tamper_fails(world, records[0], "id", 3)

    def test_conflict_family_tampers_are_detected(self) -> None:
        world = self._clean_world()
        # The 128-cell world has no borders, and the conflict builder derives
        # candidates from borders only, so the replay expects zero conflicts.
        # If this precondition ever changes, the conflict *record* builder
        # becomes reachable and deserves its own field-level tampers here.
        self.assertEqual(world["borders"], [], "canonical world unexpectedly has borders")
        self.assertEqual(world["conflicts"], [], "canonical world unexpectedly has conflicts")
        self.assertEqual(world["summary"]["conflict_count"], 0)

        with self.subTest(tamper="extra_conflict_record"):
            self._assert_only_the_list_tamper_fails(
                world,
                world["conflicts"],
                lambda records: records.append({"id": 0}),
                "an invented conflict record",
            )
        with self.subTest(tamper="inflated_summary_conflict_count"):
            self._assert_only_the_tamper_fails(world, world["summary"], "conflict_count", 1)

    def test_summary_aggregate_tampers_are_detected(self) -> None:
        # The summary is recomputed from the replayed records, so each rolled-up
        # number is independently checked rather than trusted.
        world = self._clean_world()
        summary = world["summary"]
        cases: dict[str, Any] = {
            "population_region_count": 2,
            "estimated_world_population": 1.0,
            "mean_population_pressure": 0.9,
            "dynasty_count": 2,
            "dynastic_lineage_count": 1,
            "dynasty_root_count": 2,
            "dynasty_successor_link_count": 1,
            "max_dynasty_lineage_depth": 1,
            "mean_dynastic_continuity_index": 0.0,
            "high_intensity_conflict_count": 1,
            "high_economic_disruption_conflict_count": 1,
            "mean_conflict_intensity": 0.5,
            "mean_war_duration_years": 0.5,
            "mean_conflict_logistics_strain_index": 0.5,
            "mean_conflict_economic_disruption_index": 0.5,
            "mean_conflict_casualty_rate": 0.5,
            "max_conflict_casualty_rate": 0.5,
            # ``total_mobilized_population`` is compared with an absolute floor
            # of 1.0, so the tamper has to clear that floor to bite.
            "total_mobilized_population": 5.0,
        }
        for field, value in cases.items():
            with self.subTest(summary_field=field):
                self._assert_only_the_tamper_fails(world, summary, field, value)

    def test_model_declaration_tampers_are_detected(self) -> None:
        world = self._clean_world()
        with self.subTest(tamper="dynasty_model_deleted"):
            self._assert_only_the_removal_fails(world, world, "dynasty_model")
        with self.subTest(tamper="dynasty_model_nulled"):
            self._assert_only_the_tamper_fails(world, world, "dynasty_model", None)
        with self.subTest(tamper="dynasty_model_flag_flipped"):
            self._assert_only_the_tamper_fails(
                world, world["dynasty_model"], "deterministic", False
            )
        with self.subTest(tamper="dynasty_model_thresholds_nudged"):
            self._assert_only_the_tamper_fails(
                world, world["dynasty_model"], "dynasty_count_thresholds", [0.36, 0.67]
            )
        with self.subTest(tamper="population_model_nested_parameter"):
            self._assert_only_the_tamper_fails(
                world,
                world["population_region_model"]["density_capacity_parameters"],
                "base_people_per_km2",
                1.6,
            )
        with self.subTest(tamper="population_model_extra_key"):
            self._assert_only_the_tamper_fails(
                world, world["population_region_model"], "undeclared_extra", True
            )
        with self.subTest(tamper="conflict_model_threshold"):
            self._assert_only_the_tamper_fails(
                world, world["conflict_model"], "minimum_candidate_score", 0.25
            )
        for key in ("population_region_model", "conflict_model", "dynasty_model"):
            with self.subTest(summary_model=key):
                self._assert_only_the_tamper_fails(world, world["summary"], key, "renamed_v9")

    def test_record_family_length_tampers_are_detected(self) -> None:
        world = self._clean_world()
        for family in ("population_regions", "dynasties"):
            records = world[family]
            self.assertTrue(records, f"{family} must be non-empty for these tampers to bite")
            with self.subTest(family=family, tamper="emptied"):
                self._assert_only_the_list_tamper_fails(
                    world, records, lambda values: values.clear(), f"emptying {family}"
                )
            with self.subTest(family=family, tamper="duplicated_record"):
                self._assert_only_the_list_tamper_fails(
                    world,
                    records,
                    lambda values: values.append(dict(values[0], id=len(values))),
                    f"an extra {family} record",
                )

    def test_raw_input_tampers_break_the_replay(self) -> None:
        # The point of a causal replay is that the records are *derived*, not
        # echoed: changing an input the records were built from must invalidate
        # them even though every stored record is left untouched.
        world = self._clean_world()
        with self.subTest(raw_input="culture_continuity_index"):
            self._assert_only_the_tamper_fails(
                world, world["cultures"][0], "continuity_index", 0.01
            )
        with self.subTest(raw_input="culture_migration_pressure"):
            self._assert_only_the_tamper_fails(
                world, world["cultures"][0], "migration_pressure", 0.02
            )
        with self.subTest(raw_input="cell_flooded"):
            self._assert_only_the_tamper_fails(world, world["cells"][0], "is_water", True)
        with self.subTest(raw_input="cell_left_its_region"):
            self._assert_only_the_tamper_fails(
                world, world["cells"][0], "political_region_id", -1
            )
        with self.subTest(raw_input="state_foundation_event_year"):
            foundations = [
                event
                for event in world["historical_events"]
                if str(event.get("type", "")) == "state_foundation"
            ]
            self.assertEqual(
                len(foundations), 1, "expected exactly one state foundation to shift"
            )
            self._assert_only_the_tamper_fails(
                world, foundations[0], "year_bp", float(foundations[0]["year_bp"]) + 500.0
            )
        with self.subTest(raw_input="every_cell_fertility"):
            cells = world["cells"]
            originals = [float(cell["fertility"]) for cell in cells]
            self.assertNotEqual(
                originals, [0.99] * len(cells), "fertility already holds the tampered value"
            )
            for cell in cells:
                cell["fertility"] = 0.99

            self.assertEqual(validate_civilization_geography_replay(world), [FAILURE])

            for cell, original in zip(cells, originals, strict=True):
                cell["fertility"] = original
            self.assertEqual(
                validate_civilization_geography_replay(world),
                [],
                "restoring cell fertility must replay clean again",
            )

    def test_malformed_payloads_fail_without_raising(self) -> None:
        for name, payload in (
            ("empty_payload", {}),
            ("cells_not_a_list", {"cells": "not-a-list"}),
        ):
            with self.subTest(payload=name):
                self.assertEqual(validate_civilization_geography_replay(payload), [FAILURE])

        world = self._clean_world()
        with self.subTest(payload="conflicts_not_a_list"):
            self._assert_only_the_tamper_fails(world, world, "conflicts", {})
        with self.subTest(payload="population_record_not_a_dict"):
            records = world["population_regions"]
            self._assert_only_the_list_tamper_fails(
                world,
                records,
                lambda values: values.__setitem__(0, "not-a-dict"),
                "a non-dict population record",
            )
        with self.subTest(payload="dangling_cell_neighbor"):
            # A neighbour id that no cell owns makes the replay raise KeyError
            # inside ``_has_water_neighbor``; the validator must swallow it and
            # report the failure instead of propagating. This is the only case
            # in this file that reaches that except branch.
            self._assert_only_the_tamper_fails(
                world, world["cells"][0], "neighbors", [10**9]
            )

    def test_non_numeric_measurements_are_reported_not_raised(self) -> None:
        # Every float the validator compares goes through one tolerance helper
        # that converts the *stored* value. A payload carrying a string there
        # must be reported as a mismatch rather than raising ValueError out of
        # the helper, which is a different branch from the KeyError case above.
        world = self._clean_world()
        cases: dict[str, tuple[dict[str, Any], str]] = {
            "population_water_security": (world["population_regions"][0], "water_security_index"),
            "population_carrying_capacity": (world["population_regions"][0], "carrying_capacity"),
            "dynasty_legitimacy": (world["dynasties"][0], "legitimacy_index"),
            "summary_mean_population_pressure": (world["summary"], "mean_population_pressure"),
        }
        for name, (record, field) in cases.items():
            with self.subTest(field=name):
                self._assert_only_the_tamper_fails(world, record, field, "not-a-number")

    def test_a_cell_with_no_neighbours_has_no_local_relief(self) -> None:
        # ``_local_relief`` divides by the neighbour count, so the empty case has
        # its own early return. Zeroing the relief of one populated land cell
        # lowers that cell's hazard contribution and invalidates the region's
        # stored hazard index, population and growth rate.
        world = self._clean_world()
        cell = next(
            item
            for item in world["cells"]
            if not bool(item.get("is_water", False))
            and int(item.get("political_region_id", -1)) == 0
        )
        self.assertTrue(cell["neighbors"], "the chosen cell already has no neighbours")

        self._assert_only_the_tamper_fails(world, cell, "neighbors", [])

    def test_a_region_that_owns_no_cell_replays_as_an_empty_population(self) -> None:
        # With every cell disowned the region keeps its record but has zero area,
        # so the replay takes the early "nothing to average" path and expects an
        # all-zero population region, which the stored record is not.
        world = self._clean_world()
        cells = world["cells"]
        originals = [int(cell["political_region_id"]) for cell in cells]
        self.assertIn(0, originals, "no cell belongs to region 0, so this proves nothing")
        for cell in cells:
            cell["political_region_id"] = -1

        self.assertEqual(validate_civilization_geography_replay(world), [FAILURE])

        for cell, original in zip(cells, originals, strict=True):
            cell["political_region_id"] = original
        self.assertEqual(
            validate_civilization_geography_replay(world),
            [],
            "restoring the region membership must replay clean again",
        )

    def _fabricated_border(self, world: dict[str, Any], index: int, **overrides: Any) -> dict[str, Any]:
        """A border segment the payload never declared, appended to ``world``.

        Borders are not an input to the population replay, so appending one
        leaves the population comparison passing and lets the conflict builder
        run — which is the only way to reach it from a 128-cell world.
        """
        cells = world["cells"]
        border: dict[str, Any] = {
            "id": index,
            "cell_a": int(cells[2 * index]["id"]),
            "cell_b": int(cells[2 * index + 1]["id"]),
            "region_a": 0,
            "region_b": 1,
            "type": "mountain",
            "barrier_score": 0.9,
            "length_km": 100.0,
        }
        border.update(overrides)
        world["borders"].append(border)
        return border

    def test_a_fabricated_border_makes_the_conflict_model_expect_a_conflict(self) -> None:
        # A fabricated segment with nothing disqualifying it does invalidate the
        # payload: the model expects a conflict the payload never declared.
        world = self._clean_world()
        self.assertEqual(world["borders"], [], "the fabricated segment must be the only border")

        self._fabricated_border(world, 0)

        self.assertEqual(validate_civilization_geography_replay(world), [FAILURE])

    def test_borders_the_conflict_model_discards_leave_the_replay_clean(self) -> None:
        # Two independent candidate filters. Each case injects a *qualifying*
        # segment, breaks exactly one of its fields, and requires the replay to
        # stay clean -- then repairs that one field and requires the very same
        # segment to be fatal again. Without the repair leg a clean result would
        # also be what an injection that never happened looks like, so the third
        # leg is what ties it to the named field.
        cases: dict[str, tuple[str, Any]] = {
            # A segment missing one of its two regions or cells is skipped.
            "unknown_region": ("region_a", -1),
            "unknown_cell": ("cell_b", -1),
            # A segment whose candidate score cannot reach 0.24 is skipped: the
            # intensity floor is a clamp at zero, so a hugely negative barrier
            # leaves only the fertility term, which is at most 0.08.
            "score_below_the_candidate_threshold": ("barrier_score", -10.0),
        }
        for name, (field, disqualifying) in cases.items():
            with self.subTest(border=name):
                world = self._clean_world()
                border = self._fabricated_border(world, 0)
                qualifying = border[field]
                self.assertNotEqual(
                    qualifying,
                    disqualifying,
                    f"{field!r} already holds {disqualifying!r}; this tamper changes nothing",
                )
                border[field] = disqualifying

                self.assertEqual(
                    validate_civilization_geography_replay(world),
                    [],
                    "a discarded border candidate must not change the replay",
                )

                border[field] = qualifying
                self.assertEqual(
                    validate_civilization_geography_replay(world),
                    [FAILURE],
                    f"repairing {field!r} must make the same segment a conflict candidate "
                    "again, otherwise the clean result above proves nothing",
                )

    def test_a_conflict_between_two_unknown_regions_is_a_stalemate(self) -> None:
        # Neither region has a population record, so both sides mobilise nothing
        # and the force advantage is exactly zero — the stalemate branch of the
        # outcome model. The payload declares no conflict at all, so it fails.
        world = self._clean_world()
        self._fabricated_border(world, 0, region_a=7, region_b=8)

        self.assertEqual(validate_civilization_geography_replay(world), [FAILURE])

    def test_late_maximum_intensity_conflicts_land_in_the_oldest_era(self) -> None:
        # The chronology model dates a conflict from its intensity plus a fixed
        # offset per earlier region pair, so the oldest era (before 2400 BP) can
        # only be reached by a maximum-intensity conflict that is at least the
        # twenty-fourth pair on the list. Twenty-six fabricated pairs clear it.
        world = self._clean_world()
        for index in range(26):
            self._fabricated_border(
                world, index, region_a=100 + index, region_b=200 + index, barrier_score=5.0
            )

        self.assertEqual(validate_civilization_geography_replay(world), [FAILURE])

    def _clean_bordered_world(self) -> dict[str, Any]:
        """A private copy of the smallest canonical world that has a conflict."""
        world = worlds.cached_world(BORDERED_WORLD)
        self.assertEqual(
            validate_civilization_geography_replay(world),
            [],
            "the untampered bordered world must replay clean",
        )
        self.assertEqual(len(world["conflicts"]), 1, "expected exactly one conflict record")
        return world

    def test_conflict_record_field_tampers_are_detected(self) -> None:
        # The conflict record comparison the 128-cell world can never reach:
        # exact keys first, then the tolerance keys, then the relative ones.
        world = self._clean_bordered_world()
        record = world["conflicts"][0]
        cases: dict[str, Any] = {
            "era_id": 0,
            "region_a": 5,
            "culture_b": -1,
            "cause": "sacred_site",
            "outcome": "stalemate",
            "contested_cell_id": 0,
            "start_year_bp": float(record["start_year_bp"]) + 5.0,
            "war_duration_years": float(record["war_duration_years"]) + 5.0,
            "intensity": float(record["intensity"]) - 0.02,
            "water_stress": float(record["water_stress"]) - 0.02,
            "casualty_rate": float(record["casualty_rate"]) + 0.02,
            "logistics_strain_index": float(record["logistics_strain_index"]) - 0.02,
            "economic_disruption_index": float(record["economic_disruption_index"]) - 0.02,
            "mobilized_population": float(record["mobilized_population"]) * 1.5,
            "region_a_force_estimate": float(record["region_a_force_estimate"]) * 1.5,
            "estimated_casualties": float(record["estimated_casualties"]) * 1.5,
        }
        for field, value in cases.items():
            with self.subTest(conflict_field=field):
                self._assert_only_the_tamper_fails(world, record, field, value)

    def test_borders_stripped_of_their_regions_erase_the_conflict(self) -> None:
        # The mirror of the fabricated-border cases: with every real segment
        # disqualified the model expects no conflict at all, while the payload
        # still declares one.
        world = self._clean_bordered_world()
        borders = world["borders"]
        originals = [int(border["region_a"]) for border in borders]
        self.assertTrue(all(value >= 0 for value in originals), "a border already lacks a region")
        for border in borders:
            border["region_a"] = -1

        self.assertEqual(validate_civilization_geography_replay(world), [FAILURE])

        for border, original in zip(borders, originals, strict=True):
            border["region_a"] = original
        self.assertEqual(validate_civilization_geography_replay(world), [])

    def test_multi_generation_dynasties_replay_and_carry_a_collapse_reason(self) -> None:
        # A world whose succession pressure clears 0.36 splits a region's line
        # into two dynasties, which is what makes the collapse-reason ladder and
        # the parent/child/successor links reachable at all: only a dynasty that
        # is *not* the last of its region gets a reason other than "continuity".
        world = _one_off_world(MULTI_DYNASTY_WORLD)
        self.assertEqual(
            validate_civilization_geography_replay(world),
            [],
            "the one-off multi-dynasty world must replay clean",
        )
        reasons = [str(dynasty["collapse_reason"]) for dynasty in world["dynasties"]]
        self.assertTrue(all(int(region["route_count"]) > 0 for region in world["political_regions"]))
        self.assertTrue(all(0.36 < float(d["succession_pressure"]) < 0.66 for d in world["dynasties"] if d["lineage_depth"] == 0))
        self.assertEqual(reasons, ["succession_crisis", "continuity", "succession_crisis", "continuity"])
        self.assertEqual([int(d["lineage_depth"]) for d in world["dynasties"]], [0, 1, 0, 1])
        self.assertEqual([int(d["parent_dynasty_id"]) for d in world["dynasties"]], [-1, 0, -1, 2])
        self.assertEqual([int(d["successor_dynasty_id"]) for d in world["dynasties"]], [1, -1, 3, -1])

        with self.subTest(tamper="collapse_reason"):
            payload = _with_private_records(world, "dynasties")
            payload["dynasties"][0]["collapse_reason"] = "conflict_defeat"

            self.assertEqual(validate_civilization_geography_replay(payload), [FAILURE])

        with self.subTest(tamper="successor_link"):
            payload = _with_private_records(world, "dynasties")
            payload["dynasties"][2]["successor_dynasty_id"] = -1

            self.assertEqual(validate_civilization_geography_replay(payload), [FAILURE])

        with self.subTest(tamper="region_retyped_as_a_mining_domain"):
            # The reason ladder reads the region's type, which is not an input to
            # the population or conflict replay, so this single field flips
            # "succession_crisis" to "resource_shock" and nothing else.
            payload = _with_private_records(world, "political_regions")
            self.assertNotEqual(payload["political_regions"][0]["type"], "mining_domain")
            self.assertNotEqual(payload["political_regions"][0]["dominant_resource"], "none")
            payload["political_regions"][0]["type"] = "mining_domain"

            self.assertEqual(validate_civilization_geography_replay(payload), [FAILURE])

    def test_route_removal_changes_the_isolated_dynasty_stage_to_trade_decline(self) -> None:
        # Downstream-only counterfactual: route removal would also affect the
        # population/conflict stages in a full world. Hold their already-derived
        # inputs fixed here and validate only dynasty records, never the altered
        # payload as a complete physical or civilization world.
        world = _one_off_world(MULTI_DYNASTY_WORLD)
        regions = [dict(region) for region in world["political_regions"]]
        region_id = 0
        region = regions[region_id]
        self.assertGreater(region["route_count"], 0)
        self.assertNotEqual(region["type"], "mining_domain")
        population = next(p for p in world["population_regions"] if p["region_id"] == region_id)
        self.assertLess(population["population_pressure"], 0.68)
        conflict_pressure = sum(c["intensity"] for c in world["conflicts"] if region_id in (c["region_a"], c["region_b"])) / 3.0
        self.assertLess(conflict_pressure, 0.45)
        region["route_count"] = 0

        # With no clamp or generation threshold crossed, the declared 0.10
        # route term changes pressure by +.10, legitimacy by -.22*.10, and
        # continuity by .34*(-.022) + .18*(-.10). All other inputs stay fixed.
        expected = [dict(record) for record in world["dynasties"]]
        changed = [record for record in expected if record["region_id"] == region_id]
        self.assertEqual(len(changed), 2)
        self.assertLess(changed[0]["succession_pressure"] + 0.10, 0.66)
        for record in changed:
            self.assertGreater(record["legitimacy_index"], 0.022)
            self.assertGreater(record["dynastic_continuity_index"], 0.02548)
            record["succession_pressure"] += 0.10
            record["legitimacy_index"] -= 0.022
            record["dynastic_continuity_index"] -= 0.02548
        changed[0]["collapse_reason"] = "trade_decline"
        replayed = _dynasty_records(regions, world["cultures"], world["historical_events"], world["population_regions"], world["conflicts"])
        self.assertEqual([record["collapse_reason"] for record in replayed], ["trade_decline", "continuity", "succession_crisis", "continuity"])
        self.assertEqual(len(replayed), len(expected))
        self.assertTrue(all(_dynasty_matches(actual, replay) for actual, replay in zip(expected, replayed, strict=True)))
        changed[0]["collapse_reason"] = "succession_crisis"
        self.assertFalse(_dynasty_matches(changed[0], replayed[0]))
        changed[0]["collapse_reason"] = "trade_decline"
        self.assertTrue(_dynasty_matches(changed[0], replayed[0]))
        self.assertGreater(world["political_regions"][region_id]["route_count"], 0)
        self.assertEqual(world["dynasties"][0]["collapse_reason"], "succession_crisis")

    def test_three_rival_regions_replay_with_conflict_defeat_dynasties(self) -> None:
        # Three regions put every region in two conflicts at once, which is the
        # only way its conflict pressure passes 0.45 and the collapse reason
        # becomes "conflict_defeat". Scoring this world's many border segments
        # also exercises exhaustion and a decisive region-B victory among the
        # selected records. Conflict-defeat collapse depends on accumulated
        # intensity, rather than requiring every selected outcome to be exhaustion.
        world = _one_off_world(RIVAL_REGION_WORLD)
        self.assertEqual(
            validate_civilization_geography_replay(world),
            [],
            "the one-off three-region world must replay clean",
        )
        self.assertEqual(len(world["political_regions"]), 3)
        self.assertEqual(len(world["conflicts"]), 3)
        for region in world["political_regions"]:
            regional = [c for c in world["conflicts"] if region["id"] in (c["region_a"], c["region_b"])]
            self.assertEqual(len(regional), 2)
            self.assertGreater(sum(c["intensity"] for c in regional) / 3.0, 0.45)
        self.assertEqual(
            [str(dynasty["collapse_reason"]) for dynasty in world["dynasties"]],
            ["conflict_defeat", "continuity"] * 3,
        )
        self.assertEqual(
            [str(conflict["outcome"]) for conflict in world["conflicts"]],
            ["exhaustion", "exhaustion", "region_b_victory"],
        )
        for conflict in world["conflicts"][:2]:
            self.assertGreater(conflict["logistics_strain_index"], 0.72)
            self.assertGreater(conflict["intensity"], 0.58)
        victory = world["conflicts"][2]
        self.assertLess(victory["logistics_strain_index"], 0.72)
        self.assertGreater(victory["region_b_force_estimate"], victory["region_a_force_estimate"])

        with self.subTest(tamper="conflict_outcome"):
            payload = _with_private_records(world, "conflicts")
            payload["conflicts"][0]["outcome"] = "border_shift"

            self.assertEqual(validate_civilization_geography_replay(payload), [FAILURE])

        with self.subTest(tamper="collapse_reason"):
            payload = _with_private_records(world, "dynasties")
            payload["dynasties"][0]["collapse_reason"] = "succession_crisis"

            self.assertEqual(validate_civilization_geography_replay(payload), [FAILURE])
