"""Causal-replay coverage for :mod:`magic_geo.cultural_geography_validation`.

``validate_cultural_geography_replay`` recomputes the whole deterministic
cultural model (culture regions, language regions, sacred areas and ruins) from
the generated world and compares it record by record, so a passing payload
cannot be hand-built: the happy path runs the real canonical world, and every
failure case starts from that world and applies exactly one tamper.

Two devices keep the failure cases honest.  :func:`_set` refuses to write a
value a field already holds, so a tamper can never silently become a no-op that
"passes" against an untouched world.  :meth:`assert_rejected` re-validates the
pristine copy before mutating it, so a rejection is always attributable to the
tamper rather than to drift in the generated world.  The complementary
:meth:`assert_accepted` cases pin the other side of every tolerance: the
validator compares floats with per-field tolerances and ignores unknown keys,
so the rejections below cannot be explained by "any edit at all fails".
"""

from __future__ import annotations

import copy
from typing import Any, Callable
from unittest import TestCase

from support import worlds

from magic_geo.api import generate_world
from magic_geo.cultural_geography import (
    enrich_world_with_cultural_geography_models,
)
from magic_geo.cultural_geography_validation import validate_cultural_geography_replay

#: The single message the validator returns for any mismatch.
FAILURE = "cultural geography model or causal replay invalid"

CANONICAL_WORLD = "replay_128"

#: A canonical world with two political regions, so a border segment can join
#: two different cultures.
TWO_REGION_WORLD = "mid_512"

#: The current seasonal fixture with two separate languages before a new
#: interregional trade connection. Two political regions alone do not ensure it.
TWO_LANGUAGE_WORLD = "language_contact_256"

#: A one-off configuration (``mesh.cell_count``, ``run.seed``) generated by this
#: file alone: the smallest found whose two languages share one family, which is
#: what gives the younger one a parent and a *derived* divergence age rather than
#: the root age formula.
SHARED_FAMILY_WORLD = (192, 2718)

#: The top-level keys the validator reads. Every tamper needs its own private
#: copy, and deep-copying the whole 191-key world 100+ times dominates this
#: file's runtime, so the copies are restricted to these keys. Nothing is
#: taken on trust: :meth:`assert_rejected` re-validates each copy while it is
#: still pristine and :meth:`assert_accepted` expects a clean replay, so a key
#: the validator starts reading later surfaces as an immediate failure here
#: rather than as a silently weakened test.
REPLAY_KEYS = (
    "summary",
    "cells",
    "political_regions",
    "borders",
    "trade_flows",
    "settlements",
    "cultures",
    "language_regions",
    "sacred_areas",
    "ruins",
    "culture_region_model",
    "language_region_model",
    "cultural_site_model",
)

Mutation = Callable[[dict[str, Any]], Any]

#: A land signature with no sacred trigger of its own: lowland, no resource, no
#: river or lake, no ice and no tectonics. The sacred cases below add exactly the
#: field each branch is named for. ``is_closed_basin`` and the wet-and-fertile
#: pair keep the significance above the model's selection floor, so the sites are
#: still ranked and classified rather than dropped from the payload.
NEUTRAL_LAND: dict[str, Any] = {
    "resource": "none",
    "elevation_m": 200.0,
    "landform": "plain",
    "is_river": False,
    "is_lake": False,
    "water_body_type": "land",
    "is_closed_basin": True,
    "fertility": 0.8,
    "precipitation_mm_y": 700.0,
    "ice_thickness_m": 0.0,
    "boundary_convergent": 0.0,
    "boundary_transform": 0.0,
    "settlement_score": 0.5,
    "biome": "steppe",
}

#: The same, retuned for ruins: a ruin needs a slightly richer history to clear
#: its own selection floor (hence the resource, which is not one of the mined
#: ones and so does not answer the first rung of the type ladder), and no closed
#: basin, which would otherwise explain the abandonment before the rungs below.
NEUTRAL_RUIN_LAND: dict[str, Any] = {
    **NEUTRAL_LAND,
    "resource": "sedimentary_fuels",
    "is_closed_basin": False,
}


def _set(record: dict[str, Any], key: str, value: Any) -> None:
    """Write ``value`` to ``key``, refusing a write that changes nothing.

    A tamper that assigns the value the field already holds leaves a valid
    payload behind, and the test asserting rejection would then fail for a
    confusing reason (or, worse, a sibling assertion would carry it).  Raising
    here turns that mistake into an explicit error naming the field.
    """
    if key not in record:
        raise AssertionError(f"expected field {key!r} on record {sorted(record)}")
    if record[key] == value:
        raise AssertionError(f"tamper is a no-op: {key!r} is already {value!r}")
    record[key] = value


def _shift(record: dict[str, Any], key: str, delta: float) -> None:
    """Move a numeric field by ``delta``, which must be outside its tolerance."""
    if delta == 0.0:
        raise AssertionError("a zero shift is not a tamper")
    _set(record, key, float(record[key]) + delta)


def _replay_payload() -> dict[str, Any]:
    """A private, mutable copy of the canonical world's replay inputs."""
    return _payload_from(worlds.cached_world_readonly(CANONICAL_WORLD))


def _payload_from(world: dict[str, Any]) -> dict[str, Any]:
    """A private, mutable copy of ``world`` restricted to the replay inputs."""
    return copy.deepcopy({key: world[key] for key in REPLAY_KEYS})


#: Generated at most once per process, like :mod:`support.worlds` does for the
#: canonical set.
_ONE_OFF_WORLDS: dict[tuple[int, int], dict[str, Any]] = {}


def _one_off_payload(config: tuple[int, int]) -> dict[str, Any]:
    """The replay inputs of the one-off world for ``(cell_count, seed)``."""
    if config not in _ONE_OFF_WORLDS:
        cell_count, seed = config
        _ONE_OFF_WORLDS[config] = generate_world(
            worlds.build_config(**{"mesh.cell_count": cell_count, "run.seed": seed})
        )
    return _payload_from(_ONE_OFF_WORLDS[config])


def _model_stub(**overrides: Any) -> dict[str, Any]:
    """A minimal payload carrying the real model descriptors.

    Built through the producer, :func:`enrich_world_with_cultural_geography_models`,
    so it clears the descriptor gate at the top of the validator.  Overrides are
    applied *after* enrichment, so a deliberately malformed collection still
    reaches the shape guards below that gate instead of being rejected for a
    missing descriptor.
    """
    payload = enrich_world_with_cultural_geography_models(
        {
            "cells": [],
            "cultures": [],
            "language_regions": [],
            "sacred_areas": [],
            "ruins": [],
        }
    )
    payload.update(overrides)
    return payload


class CulturalGeographyReplayValidationTests(TestCase):
    def assert_rejected(self, mutate: Mutation) -> None:
        """One tamper on a private copy of the canonical world must be caught.

        The pristine copy is validated first: without that control an expected
        failure could come from the world rather than from ``mutate``.
        """
        payload = _replay_payload()
        self.assertEqual(
            validate_cultural_geography_replay(payload),
            [],
            "untampered copy must replay cleanly or the tamper proves nothing",
        )

        mutate(payload)

        self.assertEqual(validate_cultural_geography_replay(payload), [FAILURE])

    def assert_accepted(self, mutate: Mutation) -> None:
        """An edit the validator is specified to tolerate must still replay."""
        payload = _replay_payload()
        mutate(payload)

        self.assertEqual(validate_cultural_geography_replay(payload), [])

    def test_canonical_world_replays_without_failures(self) -> None:
        payload = worlds.cached_world_readonly(CANONICAL_WORLD)

        self.assertEqual(validate_cultural_geography_replay(payload), [])

    def test_culture_record_perturbations_are_rejected(self) -> None:
        # Every field ``_culture_record_matches`` compares, exact keys first
        # then the tolerance keys, each moved well past its tolerance.
        cases: dict[str, Mutation] = {
            "language_region_id": lambda p: _set(p["cultures"][0], "language_region_id", 5),
            "homeland_region_id": lambda p: _set(p["cultures"][0], "homeland_region_id", 42),
            "type": lambda p: _set(p["cultures"][0], "type", "maritime"),
            "dominant_biome": lambda p: _set(p["cultures"][0], "dominant_biome", "tundra"),
            "dominant_resource": lambda p: _set(p["cultures"][0], "dominant_resource", "evaporites"),
            "settlement_count": lambda p: _shift(p["cultures"][0], "settlement_count", 1),
            "sacred_area_count": lambda p: _shift(p["cultures"][0], "sacred_area_count", 1),
            "ruin_count": lambda p: _shift(p["cultures"][0], "ruin_count", 1),
            "settlement_ids": lambda p: p["cultures"][0]["settlement_ids"].pop(),
            "area_km2": lambda p: _shift(p["cultures"][0], "area_km2", 1.0),
            "agricultural_area_km2": lambda p: _shift(p["cultures"][0], "agricultural_area_km2", 1.0),
            "mining_area_km2": lambda p: _shift(p["cultures"][0], "mining_area_km2", 1.0),
            "mean_fertility": lambda p: _shift(p["cultures"][0], "mean_fertility", 0.01),
            "mean_elevation_m": lambda p: _shift(p["cultures"][0], "mean_elevation_m", 1.0),
            "barrier_isolation": lambda p: _shift(p["cultures"][0], "barrier_isolation", 0.01),
            "trade_contact_index": lambda p: _shift(p["cultures"][0], "trade_contact_index", 0.01),
            "migration_pressure": lambda p: _shift(p["cultures"][0], "migration_pressure", 0.01),
            "continuity_index": lambda p: _set(p["cultures"][0], "continuity_index", 0.999),
            "estimated_age_years": lambda p: _shift(p["cultures"][0], "estimated_age_years", 10.0),
            "extra_culture_record": lambda p: p["cultures"].append(dict(p["cultures"][0])),
        }
        for name, mutate in cases.items():
            with self.subTest(field=name):
                self.assert_rejected(mutate)

    def test_language_region_record_perturbations_are_rejected(self) -> None:
        # Same treatment for every field ``_language_record_matches`` compares.
        cases: dict[str, Mutation] = {
            "parent_language_region_id": lambda p: _set(
                p["language_regions"][0], "parent_language_region_id", 0
            ),
            "family": lambda p: _set(p["language_regions"][0], "family", "arid"),
            "lineage_depth": lambda p: _shift(p["language_regions"][0], "lineage_depth", 1),
            "culture_count": lambda p: _shift(p["language_regions"][0], "culture_count", 1),
            "settlement_count": lambda p: _shift(p["language_regions"][0], "settlement_count", 1),
            "culture_ids": lambda p: _set(p["language_regions"][0], "culture_ids", []),
            "phoneme_inventory_size": lambda p: _shift(
                p["language_regions"][0], "phoneme_inventory_size", 1
            ),
            "area_km2": lambda p: _shift(p["language_regions"][0], "area_km2", 1.0),
            "barrier_isolation": lambda p: _shift(p["language_regions"][0], "barrier_isolation", 0.01),
            "trade_contact_index": lambda p: _shift(
                p["language_regions"][0], "trade_contact_index", 0.01
            ),
            "divergence_age_years": lambda p: _shift(
                p["language_regions"][0], "divergence_age_years", 10.0
            ),
            "change_rate": lambda p: _shift(p["language_regions"][0], "change_rate", 0.01),
            "phonological_complexity": lambda p: _shift(
                p["language_regions"][0], "phonological_complexity", 0.01
            ),
            "sound_shift_index": lambda p: _shift(p["language_regions"][0], "sound_shift_index", 0.01),
            "inherited_phonology_fraction": lambda p: _shift(
                p["language_regions"][0], "inherited_phonology_fraction", -0.01
            ),
            "extra_language_record": lambda p: p["language_regions"].append(
                dict(p["language_regions"][0])
            ),
        }
        for name, mutate in cases.items():
            with self.subTest(field=name):
                self.assert_rejected(mutate)

    def test_sacred_area_record_perturbations_are_rejected(self) -> None:
        cases: dict[str, Mutation] = {
            "id": lambda p: _set(p["sacred_areas"][0], "id", 5),
            "cell_id": lambda p: _set(
                p["sacred_areas"][0], "cell_id", p["sacred_areas"][1]["cell_id"]
            ),
            "culture_region_id": lambda p: _set(p["sacred_areas"][0], "culture_region_id", 7),
            "language_region_id": lambda p: _set(p["sacred_areas"][0], "language_region_id", 7),
            "type": lambda p: _set(p["sacred_areas"][0], "type", "sacred_grove"),
            "significance": lambda p: _shift(p["sacred_areas"][0], "significance", 0.01),
            "lat_deg": lambda p: _shift(p["sacred_areas"][0], "lat_deg", 0.01),
            "lon_deg": lambda p: _shift(p["sacred_areas"][0], "lon_deg", 0.01),
            # Rank order is part of the model, so the same records in the wrong
            # order must not replay.
            "records_reordered": lambda p: p.__setitem__(
                "sacred_areas", list(reversed(p["sacred_areas"]))
            ),
        }
        for name, mutate in cases.items():
            with self.subTest(field=name):
                self.assert_rejected(mutate)

    def test_ruin_record_perturbations_are_rejected(self) -> None:
        cases: dict[str, Mutation] = {
            "id": lambda p: _set(p["ruins"][0], "id", 5),
            "cell_id": lambda p: _set(p["ruins"][0], "cell_id", p["ruins"][1]["cell_id"]),
            "culture_region_id": lambda p: _set(p["ruins"][0], "culture_region_id", 7),
            "language_region_id": lambda p: _set(p["ruins"][0], "language_region_id", 3),
            "type": lambda p: _set(p["ruins"][0], "type", "ruined_city"),
            "abandonment_reason": lambda p: _set(
                p["ruins"][0], "abandonment_reason", "trade_decline"
            ),
            "significance": lambda p: _shift(p["ruins"][0], "significance", 0.01),
            "preservation_score": lambda p: _shift(p["ruins"][0], "preservation_score", 0.01),
            "lat_deg": lambda p: _shift(p["ruins"][0], "lat_deg", 0.01),
            "lon_deg": lambda p: _shift(p["ruins"][0], "lon_deg", 0.01),
            "records_reordered": lambda p: p.__setitem__("ruins", list(reversed(p["ruins"]))),
        }
        for name, mutate in cases.items():
            with self.subTest(field=name):
                self.assert_rejected(mutate)

    def test_site_record_count_mismatches_are_rejected(self) -> None:
        cases: dict[str, Mutation] = {
            "extra_sacred_area": lambda payload: payload["sacred_areas"].append({}),
            "extra_ruin": lambda payload: payload["ruins"].append({}),
            "sacred_areas_emptied": lambda payload: payload.__setitem__("sacred_areas", []),
            "ruins_emptied": lambda payload: payload.__setitem__("ruins", []),
        }
        for name, mutate in cases.items():
            with self.subTest(tamper=name):
                self.assert_rejected(mutate)

    def test_culture_assignment_of_cells_and_settlements_is_rejected(self) -> None:
        def land(payload: dict[str, Any]) -> dict[str, Any]:
            cells = [c for c in payload["cells"] if not bool(c.get("is_water", False))]
            self.assertTrue(cells, "canonical world has no land cell to tamper with")
            return cells[0]

        def water(payload: dict[str, Any]) -> dict[str, Any]:
            cells = [c for c in payload["cells"] if bool(c.get("is_water", False))]
            self.assertTrue(cells, "canonical world has no water cell to tamper with")
            return cells[0]

        cases: dict[str, Mutation] = {
            # Land cells take the culture of their political region...
            "land_cell_unknown_culture": lambda p: _set(land(p), "culture_region_id", 99),
            "land_cell_unknown_language": lambda p: _set(land(p), "language_region_id", 99),
            # ...and water cells must stay unassigned (-1).
            "water_cell_given_a_culture": lambda p: _set(water(p), "culture_region_id", 0),
            "water_cell_given_a_language": lambda p: _set(water(p), "language_region_id", 0),
            # Settlements inherit the assignment of the cell they sit on.
            "settlement_unknown_culture": lambda p: _set(p["settlements"][0], "culture_region_id", 7),
            "settlement_unassigned_culture": lambda p: _set(
                p["settlements"][0], "culture_region_id", -1
            ),
            "settlement_unknown_language": lambda p: _set(
                p["settlements"][0], "language_region_id", 7
            ),
        }
        for name, mutate in cases.items():
            with self.subTest(tamper=name):
                self.assert_rejected(mutate)

    def test_summary_counter_mismatches_are_rejected(self) -> None:
        cases: dict[str, Mutation] = {
            "culture_region_count": lambda p: _shift(p["summary"], "culture_region_count", 1),
            "language_region_count": lambda p: _shift(p["summary"], "language_region_count", 1),
            "language_lineage_count": lambda p: _shift(p["summary"], "language_lineage_count", 1),
            "sacred_area_count": lambda p: _shift(p["summary"], "sacred_area_count", 1),
            "ruin_count": lambda p: _shift(p["summary"], "ruin_count", 1),
        }
        for name, mutate in cases.items():
            with self.subTest(counter=name):
                self.assert_rejected(mutate)

    def test_summary_aggregate_mismatches_are_rejected(self) -> None:
        # The aggregates are the validator's final comparison; nothing else
        # reaches it, so each one needs its own tamper.
        cases: dict[str, Mutation] = {
            "mean_cultural_continuity": lambda p: _shift(p["summary"], "mean_cultural_continuity", 0.01),
            "mean_language_change_rate": lambda p: _shift(
                p["summary"], "mean_language_change_rate", 0.01
            ),
            "mean_phonological_complexity": lambda p: _shift(
                p["summary"], "mean_phonological_complexity", 0.01
            ),
            "mean_sound_shift_index": lambda p: _shift(p["summary"], "mean_sound_shift_index", 0.01),
            "mean_inherited_phonology_fraction": lambda p: _shift(
                p["summary"], "mean_inherited_phonology_fraction", -0.01
            ),
            "largest_culture_area_km2": lambda p: _shift(
                p["summary"], "largest_culture_area_km2", 1.0
            ),
            "culturally_assigned_land_fraction": lambda p: _shift(
                p["summary"], "culturally_assigned_land_fraction", -0.1
            ),
        }
        for name, mutate in cases.items():
            with self.subTest(aggregate=name):
                self.assert_rejected(mutate)

    def test_altered_model_descriptors_are_rejected(self) -> None:
        cases: dict[str, Mutation] = {
            "culture_region_model_removed": lambda p: p.pop("culture_region_model"),
            "language_region_model_removed": lambda p: p.pop("language_region_model"),
            "cultural_site_model_removed": lambda p: p.pop("cultural_site_model"),
            "culture_region_model_parameter_changed": lambda p: _set(
                p["culture_region_model"], "agricultural_fertility_threshold", 0.5
            ),
            "language_region_model_parameter_changed": lambda p: _set(
                p["language_region_model"], "union_volume_threshold", 55.0
            ),
            "cultural_site_model_parameter_changed": lambda p: _set(
                p["cultural_site_model"], "sacred_candidate_threshold", 0.11
            ),
            "summary_culture_region_model_renamed": lambda p: _set(
                p["summary"], "culture_region_model", "bogus_model_v1"
            ),
            "summary_language_region_model_renamed": lambda p: _set(
                p["summary"], "language_region_model", "bogus_model_v1"
            ),
            "summary_cultural_site_model_renamed": lambda p: _set(
                p["summary"], "cultural_site_model", "bogus_model_v1"
            ),
        }
        for name, mutate in cases.items():
            with self.subTest(tamper=name):
                self.assert_rejected(mutate)

    def test_duplicate_cell_ids_are_rejected(self) -> None:
        # ``cells`` is indexed by id, so a collision would silently drop a cell
        # from the replay; the validator compares the two counts instead.
        self.assert_rejected(lambda p: _set(p["cells"][1], "id", p["cells"][0]["id"]))

    def test_non_list_collections_are_rejected_before_they_can_be_indexed(self) -> None:
        # Each replacement has the *same length* as the list it replaces, so the
        # record-count checks cannot explain the rejection: only the type guard
        # can. Without it the validator would reach ``str.get`` and raise.
        def as_string(key: str) -> Mutation:
            def mutate(payload: dict[str, Any]) -> None:
                count = len(payload[key])
                self.assertGreater(count, 0, f"{key} is empty, so length parity proves nothing")
                payload[key] = "x" * count

            return mutate

        for key in ("cells", "cultures", "language_regions", "sacred_areas", "ruins", "settlements"):
            with self.subTest(collection=key):
                self.assert_rejected(as_string(key))

    def test_within_tolerance_and_unknown_field_edits_are_still_accepted(self) -> None:
        # The mirror image of the rejection tests: the validator compares floats
        # with per-field tolerances and ignores keys it does not model, so the
        # rejections above are attributable to the size of each tamper rather
        # than to the validator refusing every edit.
        cases: dict[str, Mutation] = {
            "culture_continuity_index_within_0.002": lambda p: _shift(
                p["cultures"][0], "continuity_index", 0.0005
            ),
            "culture_estimated_age_within_3.0": lambda p: _shift(
                p["cultures"][0], "estimated_age_years", 1.0
            ),
            "language_change_rate_within_0.003": lambda p: _shift(
                p["language_regions"][0], "change_rate", 0.001
            ),
            "sacred_lon_within_0.001": lambda p: _shift(p["sacred_areas"][0], "lon_deg", 0.0005),
            "ruin_preservation_within_0.001": lambda p: _shift(
                p["ruins"][0], "preservation_score", 0.0005
            ),
            "summary_mean_continuity_within_0.005": lambda p: _shift(
                p["summary"], "mean_cultural_continuity", 0.001
            ),
            "unmodelled_key_on_a_culture": lambda p: p["cultures"][0].__setitem__(
                "unmodelled_key", "ignored"
            ),
            "unmodelled_key_on_a_ruin": lambda p: p["ruins"][0].__setitem__(
                "unmodelled_key", "ignored"
            ),
        }
        for name, mutate in cases.items():
            with self.subTest(edit=name):
                self.assert_accepted(mutate)

    def test_malformed_payloads_fail_without_raising_since_entry_has_no_try_except(
        self,
    ) -> None:
        # ``validate_cultural_geography_replay`` has no exception wrapper: every
        # guard lives in ``_replay_valid``, so these must return the failure
        # string rather than propagate a TypeError/KeyError to the CLI.  The
        # last two carry real model descriptors so they clear the descriptor
        # gate and reach the shape guard each one is named for.
        payloads: dict[str, dict[str, Any]] = {
            "empty": {},
            "summary_not_a_mapping": {"summary": None},
            "cells_missing": {"summary": {}, "cultures": []},
            "cells_not_a_list": {"summary": {}, "cells": {}},
            "cells_are_not_mappings": _model_stub(cells=[1, 2, 3]),
            "collection_not_a_list": _model_stub(cells=[{"id": 0}], cultures="nope"),
        }
        for name, payload in payloads.items():
            with self.subTest(payload=name):
                self.assertEqual(validate_cultural_geography_replay(payload), [FAILURE])

    def test_non_numeric_measurements_are_rejected_not_raised(self) -> None:
        # Every float comparison goes through one tolerance helper that converts
        # the stored value, so a payload carrying a string where a measurement
        # belongs must come back as a rejection rather than a ValueError.
        cases: dict[str, Mutation] = {
            "culture_mean_fertility": lambda p: p["cultures"][0].__setitem__(
                "mean_fertility", "loamy"
            ),
            "language_change_rate": lambda p: p["language_regions"][0].__setitem__(
                "change_rate", "quick"
            ),
            "sacred_significance": lambda p: p["sacred_areas"][0].__setitem__(
                "significance", "holy"
            ),
            "summary_mean_continuity": lambda p: p["summary"].__setitem__(
                "mean_cultural_continuity", "steady"
            ),
        }
        for name, mutate in cases.items():
            with self.subTest(field=name):
                self.assert_rejected(mutate)

    def test_the_region_terrain_decides_the_culture_type(self) -> None:
        # The culture-type ladder reads region type, elevation, biome and
        # resource. The canonical region takes the river-realm rung, so each
        # case clears earlier priorities before selecting its named rung. Culture
        # type also picks the language family, so every case is rejected.
        def region_terrain(**fields: Any) -> Mutation:
            def mutate(payload: dict[str, Any]) -> None:
                region = payload["political_regions"][0]
                self.assertEqual(
                    str(region["type"]), "river_realm", "the canonical rung moved"
                )
                # A neutral type and a lowland elevation clear the maritime,
                # river and highland rungs that would otherwise answer first.
                _set(region, "type", "chiefdom")
                region["mean_elevation_m"] = 100.0
                # The seasonal region is already hot desert. Clear both
                # remaining priorities before selecting one named branch;
                # otherwise the mining case still exercises desert_oasis.
                region["dominant_biome"] = "steppe"
                region["dominant_resource"] = "none"
                region.update(fields)

            return mutate

        cases: dict[str, Mutation] = {
            "desert_oasis": region_terrain(dominant_biome="hot_desert"),
            "mining_frontier": region_terrain(dominant_resource="placer_metals"),
            "boreal_frontier": region_terrain(dominant_biome="tundra"),
            "forest_realm": region_terrain(dominant_biome="savanna"),
            "agrarian_lowland": region_terrain(dominant_biome="temperate_forest"),
        }
        for name, mutate in cases.items():
            with self.subTest(culture_type=name):
                self.assert_rejected(mutate)

    def test_a_cell_without_a_usable_position_is_infinitely_far_away(self) -> None:
        # The current world's two selected sites remain selected when one is
        # infinitely distant. Pair that acceptance with a coincident-position
        # control: zero distance crowds out a site, while a malformed vector
        # restores the published selection. No terrain or significance changes.
        payload = _replay_payload()
        self.assertEqual(validate_cultural_geography_replay(payload), [])
        sites = payload["sacred_areas"]
        self.assertEqual(len(sites), 2)
        self.assertNotEqual(sites[0]["cell_id"], sites[1]["cell_id"])
        cells = {cell["id"]: cell for cell in payload["cells"]}
        first, second = (cells[site["cell_id"]] for site in sites)
        original_position = first["position_3d"]
        self.assertEqual(len(original_position), 3)
        self.assertNotEqual(original_position, second["position_3d"])
        first["position_3d"] = copy.deepcopy(second["position_3d"])
        self.assertEqual(validate_cultural_geography_replay(payload), [FAILURE])
        first["position_3d"] = [1.0, 0.0]
        self.assertEqual(validate_cultural_geography_replay(payload), [])
        first["position_3d"] = original_position
        self.assertEqual(validate_cultural_geography_replay(payload), [])

    def _rewrite_land_cells(self, payload: dict[str, Any], **fields: Any) -> None:
        """Give every land cell the same terrain signature.

        The site models rank *all* land cells and only classify the winners, so
        tampering one cell moves it down the ranking instead of changing its
        recorded type. Rewriting every land cell identically makes the winner —
        whichever it turns out to be — carry the signature under test.
        """
        land = [cell for cell in payload["cells"] if not bool(cell.get("is_water", False))]
        self.assertTrue(land, "the canonical world has no land cell")
        for cell in land:
            cell.update(fields)

    def test_the_cell_terrain_decides_the_sacred_site_type(self) -> None:
        payload = _replay_payload()
        self.assertEqual(
            {str(record["type"]) for record in payload["sacred_areas"]},
            {"volcanic_sanctuary", "mountain_shrine"},
            "the canonical sites already carry a type under test",
        )

        cases: dict[str, dict[str, Any]] = {
            "spring_oracle": {"is_lake": True},
            "sacred_grove": {"biome": "temperate_forest"},
            "desert_sanctuary": {"biome": "hot_desert"},
            # No forest, no desert and no water of its own: only a marine
            # neighbour is left to classify it.
            "ancestral_coast": {"biome": "steppe"},
            # ...and with no neighbours at all the ladder falls through to its
            # default, which also zeroes the local relief term of every score.
            "inland_default_grove": {"biome": "steppe", "neighbors": []},
        }
        for name, fields in cases.items():
            with self.subTest(sacred_type=name):
                self.assert_rejected(
                    lambda p, extra=fields: self._rewrite_land_cells(
                        p, **{**NEUTRAL_LAND, **extra}
                    )
                )

    def test_the_cell_terrain_decides_the_ruin_type_and_abandonment_reason(self) -> None:
        payload = _replay_payload()
        self.assertEqual(
            {str(record["type"]) for record in payload["ruins"]},
            {"desert_outpost", "mountain_fortress"},
            "the canonical ruins already carry a type under test",
        )
        self.assertEqual(
            {str(record["abandonment_reason"]) for record in payload["ruins"]},
            {"aridity", "tectonic_hazard"},
            "the canonical ruins already carry a reason under test",
        )

        cases: dict[str, dict[str, Any]] = {
            # Ice with no neighbours: no harbour rung can answer first, so the
            # glacial rung classifies the ruin and the same ice explains why it
            # was abandoned.
            "glacial_relic_type": {"ice_thickness_m": 50.0, "neighbors": []},
            "glaciation_reason": {"ice_thickness_m": 50.0},
            # Nothing hostile is left, so the reason falls to the settlement
            # score on either side of its 0.48 threshold.
            "trade_decline_reason": {"settlement_score": 0.1},
            "frontier_isolation_reason": {"settlement_score": 0.6},
        }
        for name, fields in cases.items():
            with self.subTest(ruin_case=name):
                self.assert_rejected(
                    lambda p, extra=fields: self._rewrite_land_cells(
                        p, **{**NEUTRAL_RUIN_LAND, **extra}
                    )
                )

    def test_borders_and_flows_outside_the_culture_map_are_ignored(self) -> None:
        # Both aggregates skip records they cannot attribute to two cultures.
        # Every "ignored" case is paired with a control that differs from it in
        # one region id and *is* fatal, so a clean result here can only mean the
        # record was discarded -- never that the injection failed to happen.
        payload = _replay_payload()
        self.assertEqual(len(payload["political_regions"]), 1)

        with self.subTest(ignored="flow_from_an_unknown_region"):
            self.assert_accepted(
                lambda p: p["trade_flows"].append(
                    {
                        "id": len(p["trade_flows"]),
                        "region_from": -1,
                        "region_to": 0,
                        "volume_index": 900.0,
                        "friction": 0.1,
                    }
                )
            )

        # The two ignored border shapes run on the two-region world instead of
        # this one, because only there does an *attributable* border of the very
        # same shape exist: each case below differs from the fatal control by a
        # single region id, which is what proves the segment was discarded
        # rather than never appended.
        def bordered(region_a: int, region_b: int) -> list[str]:
            payload = _payload_from(worlds.cached_world_readonly(TWO_REGION_WORLD))
            self.assertEqual(validate_cultural_geography_replay(payload), [])
            payload["borders"].append(
                {
                    "id": len(payload["borders"]),
                    "region_a": region_a,
                    "region_b": region_b,
                    "barrier_score": 0.9,
                    "length_km": 9000.0,
                }
            )
            return validate_cultural_geography_replay(payload)

        with self.subTest(ignored="border_with_an_unknown_region"):
            self.assertEqual(bordered(-1, 0), [])
        with self.subTest(ignored="border_inside_one_region"):
            self.assertEqual(bordered(0, 0), [])
        with self.subTest(control="border_between_two_regions"):
            # Same length, same barrier score, same payload: only the second
            # region id differs from the two cases above.
            self.assertEqual(bordered(0, 1), [FAILURE])

        with self.subTest(control="flow_inside_one_region"):
            # Same shape, but attributable: it moves the culture's trade contact
            # index, so the injection is not inert.
            self.assert_rejected(
                lambda p: p["trade_flows"].append(
                    {
                        "id": len(p["trade_flows"]),
                        "region_from": 0,
                        "region_to": 0,
                        "volume_index": 900.0,
                        "friction": 0.1,
                    }
                )
            )

    def test_a_trade_flow_merges_two_separate_language_regions(self) -> None:
        with self.subTest(control="flow_that_merges_two_language_regions"):
            # Above a volume of 70 at a friction of at most 0.92 the language
            # model unions the two cultures into a single language region, so
            # this flow is not merely counted: it changes the language map that
            # the payload's two separate language records describe.
            payload = _payload_from(worlds.cached_world_readonly(TWO_LANGUAGE_WORLD))
            self.assertEqual(validate_cultural_geography_replay(payload), [])
            self.assertEqual(len(payload["language_regions"]), 2)
            self.assertEqual(
                [language["culture_ids"] for language in payload["language_regions"]],
                [[0], [1]],
            )
            self.assertEqual(
                [culture["homeland_region_id"] for culture in payload["cultures"]],
                [0, 1],
            )
            payload["trade_flows"].append(
                {
                    "id": len(payload["trade_flows"]),
                    "region_from": 0,
                    "region_to": 1,
                    "volume_index": 100.0,
                    "friction": 0.5,
                }
            )

            self.assertEqual(validate_cultural_geography_replay(payload), [FAILURE])

    def test_a_language_that_inherits_a_family_gets_a_derived_divergence_age(self) -> None:
        # The lineage model only gives a language a parent when another language
        # of the *same family* has more area, and then dates it from its own
        # isolation and trade contact instead of the root formula. The canonical
        # world has a single language, so this needs a one-off world.
        payload = _one_off_payload(SHARED_FAMILY_WORLD)
        self.assertEqual(
            validate_cultural_geography_replay(payload),
            [],
            "the one-off shared-family world must replay clean",
        )
        languages = payload["language_regions"]
        self.assertEqual(len(languages), 2)
        self.assertEqual({str(language["family"]) for language in languages}, {"coastal"})
        self.assertEqual(int(languages[0]["parent_language_region_id"]), -1)
        self.assertEqual(int(languages[1]["parent_language_region_id"]), 0)
        self.assertEqual(int(languages[1]["lineage_depth"]), 1)

        for field, delta in (("divergence_age_years", 40.0), ("sound_shift_index", 0.02)):
            with self.subTest(child_field=field):
                payload = _one_off_payload(SHARED_FAMILY_WORLD)
                _shift(payload["language_regions"][1], field, delta)

                self.assertEqual(validate_cultural_geography_replay(payload), [FAILURE])
