"""Empirical calibration: reading reference datasets, deriving target
ranges from them, and scoring generated worlds against those targets.

Layered so imports only ever point downwards: errors -> _helpers ->
readers -> sampling -> derive, with evaluate/reports independent."""

from __future__ import annotations

from ._constants import *  # noqa: F401,F403
from .errors import CalibrationError
from ._helpers import (
    _target_items,
    _source_items,
    _target_float,
    _target_text,
    _optional_float,
    _optional_int,
    _file_sha256,
    _source_provenance,
    _percentile,
    _numeric_statistic,
    _haversine_km,
    _projected_ring_area_km2,
    _geographic_ring_area_km2,
    _segment_length_km,
    _ring_area_km2,
    _part_ranges,
    _point_in_ring,
    _point_in_polygon_feature,
    _fibonacci_points,
    _symmetric_nearest_neighbors,
    _masked_component_sizes,
    _comma_separated_floats,
    _next_nonempty_line,
    _nearest_coordinate_index,
    _normalize_vector_coordinate_system,
    _coordinate_system_from_prj_text,
    _prj_path_for_shapefile,
    _coordinate_system_for_vector,
)
from .sources import load_calibration_targets, load_calibration_sources
from .readers import (
    _read_esri_ascii_grid,
    _read_geojson_values,
    _read_shapefile_records,
    _dbf_path_for_shapefile,
    _read_dbf_numeric_columns_from_bytes,
    _read_dbf_numeric_values_from_bytes,
    _iter_dbf_numeric_records,
    _read_dbf_numeric_values,
    _read_shapefile_values,
    _read_opendap_ascii_grid,
    _worldclim_monthly_samples,
    _hydrobasins_catalog_summary,
    _hydrobasins_catalog_statistic,
    _hydrorivers_archive_summary,
    _hydrorivers_archive_statistic,
)
from .sampling import (
    _fibonacci_coastal_land_fraction,
    _fibonacci_relief_statistic,
    _fibonacci_worldclim_statistic,
)
from .derive import (
    _infer_source_format,
    _source_values,
    _shapefile_coordinate_metadata,
    _shapefile_uses_coordinate_system,
    derive_calibration_targets,
)
from .evaluate import score_range, _world_metric_values, evaluate_calibration_targets
from .reports import write_calibration_markdown, write_target_derivation_markdown

__all__ = [
    "CalibrationError",
    "_FIBONACCI_COASTAL_STATISTIC",
    "_FIBONACCI_RELIEF_STATISTICS",
    "_FIBONACCI_WORLDCLIM_STATISTICS",
    "_HYDROBASINS_GENERATED_MIN_CENTROID_LAT_DEG",
    "_HYDROBASINS_STATISTICS",
    "_HYDRORIVERS_STATISTICS",
    "_SHA256_PATTERN",
    "_SOURCE_PROVENANCE_FIELDS",
    "_comma_separated_floats",
    "_coordinate_system_for_vector",
    "_coordinate_system_from_prj_text",
    "_dbf_path_for_shapefile",
    "_fibonacci_coastal_land_fraction",
    "_fibonacci_points",
    "_fibonacci_relief_statistic",
    "_fibonacci_worldclim_statistic",
    "_file_sha256",
    "_geographic_ring_area_km2",
    "_haversine_km",
    "_hydrobasins_catalog_statistic",
    "_hydrobasins_catalog_summary",
    "_hydrorivers_archive_statistic",
    "_hydrorivers_archive_summary",
    "_infer_source_format",
    "_iter_dbf_numeric_records",
    "_masked_component_sizes",
    "_nearest_coordinate_index",
    "_next_nonempty_line",
    "_normalize_vector_coordinate_system",
    "_numeric_statistic",
    "_optional_float",
    "_optional_int",
    "_part_ranges",
    "_percentile",
    "_point_in_polygon_feature",
    "_point_in_ring",
    "_prj_path_for_shapefile",
    "_projected_ring_area_km2",
    "_read_dbf_numeric_columns_from_bytes",
    "_read_dbf_numeric_values",
    "_read_dbf_numeric_values_from_bytes",
    "_read_esri_ascii_grid",
    "_read_geojson_values",
    "_read_opendap_ascii_grid",
    "_read_shapefile_records",
    "_read_shapefile_values",
    "_ring_area_km2",
    "_segment_length_km",
    "_shapefile_coordinate_metadata",
    "_shapefile_uses_coordinate_system",
    "_source_items",
    "_source_provenance",
    "_source_values",
    "_symmetric_nearest_neighbors",
    "_target_float",
    "_target_items",
    "_target_text",
    "_world_metric_values",
    "_worldclim_monthly_samples",
    "derive_calibration_targets",
    "evaluate_calibration_targets",
    "load_calibration_sources",
    "load_calibration_targets",
    "score_range",
    "write_calibration_markdown",
    "write_target_derivation_markdown",
]
